dirty_cat/similarity_encoder.py
=> Adding docstring to SimilarityEncoder

dirty_cat/datasets/__init__.py, dirty_cat/datasets/fetching.py, doc/index.rst
Adds all datasets on the docs.
=> [MRG] Datasets doc

dirty_cat/similarity_encoder.py, dirty_cat/test/test_similarity_encoder.py
`get_most_frequent` was broken, which was hidden by broken tests.
=> Fix "most_frequent" prototyping

examples/03_midwest_survey.py
I was explaining this example to a friend, and found that it lacked printing the values, to explain what this is about.
=> DOC: better midwest example

.gitignore, dirty_cat/similarity_encoder.py
Replace _BaseEncoder by OneHotEncoder
=> Subclass SimilarityEncoder of OneHotEncoder

dirty_cat/similarity_encoder.py
Improve memory usage and improve speed.
=> OPTIM: better ngram-similarity

CHANGES.rst, dirty_cat/similarity_encoder.py, dirty_cat/test/test_similarity_encoder.py, examples/04_scalability.py
Shows difference in memory consumption between a float64 and float32
=> Added example with dtype float32

dirty_cat/datasets/fetching.py
=> FIX update medical charge csv filename

dirty_cat/datasets/fetching.py
Side effect of me looking back at the `fetching.py` code.
=> CLN remove commands under the main condition

doc/conf.py
=> DOC 'scikit-learn'->'sklearn' sphinx_gallery_conf

codecov.yml
Fix https://github.com/dirty-cat/dirty_cat/issues/120
=> [WIP] add 1% threshold in codecove yml

examples/02_fit_predict_plot_employee_salaries.py
On my laptop, example 02 raise ValueError because of Nan in "gender". 
Here is a possible fix. (which slightly rise the variance in scores)
=> Fix examples_02

.travis.yml
With different Python versions, and different optional dependencies (pandas)
=> Test different environments under travis

CHANGES.rst, dirty_cat/similarity_encoder.py, dirty_cat/test/test_similarity_encoder.py
References Issue #124 Add support for missing values in the encoders
Changes: Added missing values support for similarity encoder
=> [MRG] handle missing values for similarity encoder

CHANGES.rst, dirty_cat/target_encoder.py, dirty_cat/test/test_target_encoder.py
References Issue #124 Add support for missing values in the encoders
Changes: Added missing values support for target encoder
=> [MRG] handle missing values for target encoder

examples/05_scaling_non_linear_models.py
Fix inner :ref: in examples 05
=> fix reference in examples 05

dirty_cat/minhash_encoder.py, dirty_cat/test/test_minhash_encoder.py
References Issue #124 Add support for missing values in the encoders
Changes: Added missing values support for minhash encoder
=> [MRG] minhash handle missing values

.travis.yml, build_tools/travis/install.sh
Hi,
I made some changes to the Travis pipeline in order to include tests on Scikit-learn's nightly builds, as advised by @GaelVaroquaux.
The CI tests were successful on my fork.
Please let me know if anything's off.
=> Include Scikit-learn's nightly builds to the Travis pipeline.

dirty_cat/minhash_encoder.py, dirty_cat/test/test_minhash_encoder.py
Regression test for cache overflow problem (rows are encoded with -1s). 
Fixes: #146
=> regression test for cache overflow

.travis.yml
=> Update travis to test on latest Python

doc/conf.py
Try to restore a working build.
=> Fix Sphinx-gallery

.github/workflows/testing.yml, README.rst, build_tools/github/dependencies.sh, build_tools/github/install.sh, build_tools/github/test.sh, dirty_cat/test/test_gap_encoder.py, requirements-min.txt, requirements.txt
See #171 
This PR proposes to run tests on Github actions.
Note: I've used the structure we use for Nilearn but I can adapt if needed.
=> Enable testing on GitHub actions

dirty_cat/similarity_encoder.py, dirty_cat/test/test_similarity_encoder.py
=> Fix AttributeError drop_idx_ SimilarityEncoder

build_tools/circle/build_doc.sh, doc/conf.py
To have social-media summaries
=> DOC: add sphinxext-opengraph

doc/conf.py
This is useful for instance social-media links
=> [WIP] Try to add "Dirty cat" to the page titles

.circleci/config.yml, examples/02_fit_predict_plot_employee_salaries.py
Tree based models work better. Trying this out to see if the example takes too long.
=> Use gradient boosting instead of ridge

doc/conf.py
=> Fix type hinting in generated doc

doc/_static/custom.css, doc/_templates/class.rst
A more readable docstring page
=> DOC: style docstring pages

doc/_static/custom.css, doc/binder/requirements.txt, doc/conf.py
Closes #186
Unfortunately, I believe that this needs to be merged in master to be tested.
=> DOC: Add binder

dirty_cat/super_vectorizer.py, dirty_cat/test/test_super_vectorizer.py
=> Fix SV not raising error when not fitted

dirty_cat/gap_encoder.py, dirty_cat/test/test_gap_encoder.py, dirty_cat/utils.py
Similar to #128
Add missing values handling in the GapEncoder.
Required for #178
=> Handle missing in GapEncoder

benchmarks/get_results.py, benchmarks/supervectorizer_tuning.py, dirty_cat/super_vectorizer.py
Following some benchmarks we made, I've tuned the default parameters of the SuperVectorizer to reflect these results.
Finer tuning is possible, but it already took almost two weeks to get these results, so for now it'll do.
=> Tune SuperVectorizer

README.rst, doc/_static/custom.css, doc/index.rst
Fixes https://github.com/dirty-cat/dirty_cat/issues/227
=> DOC: Rework homepage

examples/04_scaling_non_linear_models.py
Hi,
While I was reading example 4 on the site, I noticed some minor typos and links that don't work and need to be updated.
Thanks.
=> Typos and links corrected

dirty_cat/similarity_encoder.py
=> Fix missing infrequent attribute for scikit-learn>1.1.0

examples/06_datetime_encoder.py
1. Lines shorter to avoid horizontal scrolling
2. Remove one header, which did not capture an important message
=> Cosmit on DateTimeEncoder example

dirty_cat/datasets/fetching.py
=> add openml url to fetching functions

benchmarks/similarity_scores_time_benchmark.py
Hi,
This benchmark was no longer working. There were a few problems with importing/preprocessing data that I fixed.
Thanks.
=> Fix similarity encoder benchmark

dirty_cat/gap_encoder.py, dirty_cat/similarity_encoder.py, requirements-min.txt
=> Bump sklearn from 0.21 to 0.22

CODE_OF_CONDUCT.md
=> DOC Add Code of conduct

RELEASE_PROCESS.md
A while ago, I wrote this little document, which describes the release process of dirty_cat.
I though it might be useful to add it for future contributors :)
=> Add release process

dirty_cat/datetime_encoder.py, dirty_cat/gap_encoder.py, dirty_cat/super_vectorizer.py, dirty_cat/test/test_gap_encoder.py
=> Normalize `get_feature_names` handling

.circleci/config.yml, .github/workflows/testing.yml, CHANGES.rst, README.rst, build_tools/circle/build_doc.sh, setup.py
=> Bump min Python version

.github/workflows/main.yml
Fixes https://github.com/dirty-cat/dirty_cat/issues/310.
=> CI Add informative message to mention the rendered docs

build_tools/circle/build_doc.sh, build_tools/circle/list_versions.py
scikit-learn related functionality from our building tool
=> [BUILD] Remove unused functionality

build_tools/circle/build_doc.sh
The build is failing on master. Removing to clean stuff
=> Remove buggy file

CHANGES.rst
=> Fix release notes

CHANGES.rst
Fix #338 and other small issues.
=> Fix links to scikit-learn in release notes

.github/workflows/codeql-analysis.yml
Adds CodeQL, a tool for finding vulnerabilities and mistakes in the code.
It was recommended by GitHub, let's see if this can be useful for us.
=> Implement CodeQL

.pre-commit-config.yaml
=> Limit flake8 run

doc/_static/custom.css, doc/_templates/about.html, doc/index.rst
Improve the documentation:
- make the `pip install` readable with mono font
- add the version number when browsing the doc
=> DOC add version and improve install

examples/01_dirty_categories.py
Solve the current issue.
I will check if the function is available for older scikit-learn
=> FIX use sklearn.utils.fixes.parse_version instead of private Version

RELEASE_PROCESS.rst
=> MAINT update the instructions for releasing dirty_cat

doc/_static/custom.css, doc/_templates/about.html
Adds a version switcher for the docs.
=> Multiple versions

dirty_cat/_datetime_encoder.py, dirty_cat/tests/test_docstrings.py
=> DOC Ensures that DatetimeEncoder.fit passes numpydoc validation

dirty_cat/_datetime_encoder.py, dirty_cat/tests/test_docstrings.py
=> DOC Ensures that DatetimeEncoder.transform passes numpydoc validation

dirty_cat/_target_encoder.py
Fix part of #373 
Inspired from [sklearn's OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html).
=> Add simple reproducible example to TargetEncoder

CHANGES.rst, dirty_cat/_minhash_encoder.py, dirty_cat/tests/test_minhash_encoder.py
=> [MRG] BUG: handle None in MinHashEncoder

CONTRIBUTING.rst
=> Add more info on branch creation

.github/workflows/codeql-analysis.yml, .github/workflows/testing.yml, README.rst, build_tools/circle/build_doc.sh, build_tools/circle/checkout_merge_commit.sh, codecov.yml, doc/conf.py, examples/06_joining_tables_with_FuzzyJoin.py
=> Rename "master" branch to "main"

dirty_cat/_fuzzy_join.py, dirty_cat/tests/test_fuzzy_join.py
=> Add pandas.merge and fuzzy_join comparison tests

dirty_cat/_target_encoder.py, dirty_cat/tests/test_target_encoder.py
Linked to #371 
Code coverage for target_encoder up from 78% to 97%
=> improve coverage of TargetEncoder

dirty_cat/_gap_encoder.py
Fix part of #373 and some small docstring issues.
=> Add simple reproducible example to GapEncoder

dirty_cat/tests/test_fast_hash.py, dirty_cat/tests/test_utils.py, dirty_cat/tests/utils.py
Fix part of #376 for test of the fast_hash
=> Remove fetching data for test of fast_hash

dirty_cat/_super_vectorizer.py, dirty_cat/tests/test_docstrings.py
=> DOC Ensures that `SuperVectorizer` passes numpydoc validation

dirty_cat/tests/test_gap_encoder.py, dirty_cat/tests/test_utils.py, dirty_cat/tests/utils.py
Fix #376 for the GapEncoder.
This also helped tests run much faster.
=> Remove fetching data for test of GapEncoder

dirty_cat/_gap_encoder.py, dirty_cat/_target_encoder.py
Fix small errors in the examples published on the encoder's page.
=> Fix encoder reproducible examples

dirty_cat/_similarity_encoder.py
=> Add simple reproducible example to SimilarityEncoder

dirty_cat/tests/test_gap_encoder.py, dirty_cat/tests/utils.py
=> Set random state parameter in test data generation function

dirty_cat/_datetime_encoder.py, dirty_cat/_gap_encoder.py, dirty_cat/_similarity_encoder.py, dirty_cat/_super_vectorizer.py, dirty_cat/_utils.py, dirty_cat/tests/test_gap_encoder.py, dirty_cat/tests/test_similarity_encoder.py, dirty_cat/tests/test_super_vectorizer.py, dirty_cat/tests/test_utils.py
=> Use `sklearn.utils.parse_version` instead of `Version`

dirty_cat/datasets/_fetching.py, dirty_cat/datasets/tests/test_fetching.py
=> Fix random fetching error

dirty_cat/_minhash_encoder.py
=> DOC Add simple reproducible example to MinHash Encoder

dirty_cat/_datetime_encoder.py, dirty_cat/tests/test_docstrings.py
=> Fix the doctring for DateTimeEncoder 

dirty_cat/_similarity_encoder.py
=> BUG Change name of ngram_similarity function

dirty_cat/_datetime_encoder.py
=> DOC Add simple reproducible example to DatetimeEncoder

dirty_cat/_gap_encoder.py, dirty_cat/tests/test_docstrings.py
=> DOC Ensures that `GapEncoder` passes numpydoc validation

dirty_cat/_similarity_encoder.py, dirty_cat/tests/test_similarity_encoder.py
Fix part of #371 
Coverage is up from 90 to 99%
=> ENH Improve coverage of SimilarityEncoder

doc/conf.py
Supersedes #435 
Removes the dash altogether.
=> Remove emdash in config

CHANGES.rst
This PR is above all to test the circleCI integration.
=> Minor doc change

dirty_cat/_target_encoder.py
Fix simple error when reproducing the example
=> FIX Error in simple reproducible example of Target Encoder

dirty_cat/_target_encoder.py
=> DOC Fix `handle_unknown` docstring of the TargetEncoder

examples/05_fuzzy_joining_and_FeatureAugmenter.py
Small wording on the fuzzy join example to make the difference and complementarity of the fuzzy_join function and the FeatureAugmenter more clear.
=> DOC: fuzzy join example

dirty_cat/_gap_encoder.py, dirty_cat/_minhash_encoder.py, dirty_cat/_similarity_encoder.py, dirty_cat/_super_vectorizer.py, dirty_cat/tests/test_datetime_encoder.py, dirty_cat/tests/test_gap_encoder.py, dirty_cat/tests/test_minhash_encoder.py, dirty_cat/tests/test_similarity_encoder.py, dirty_cat/tests/test_super_vectorizer.py, dirty_cat/tests/test_target_encoder.py
This gives an intelligible error if someone calls `transform`. Solves #462
=> Use `check_is_fitted` for all dirty_cat transformers.

.pre-commit-config.yaml
=> FIX pre-commit checks

dirty_cat/_deduplicate.py
=> DOC Add simple reproducible example to deduplicate

dirty_cat/_datetime_encoder.py, dirty_cat/_deduplicate.py, dirty_cat/_feature_augmenter.py, dirty_cat/_fuzzy_join.py, dirty_cat/_gap_encoder.py, dirty_cat/_minhash_encoder.py, dirty_cat/_similarity_encoder.py, dirty_cat/_table_vectorizer.py, dirty_cat/_target_encoder.py
=> DOC add See also to docstring

dirty_cat/_feature_augmenter.py
Add a see also to the ken embeddings from the FeatureAugmenter
=> DOC: Add a see-also

dirty_cat/datasets/_fetching.py, dirty_cat/datasets/tests/test_fetching.py
Following the CI errors of #453 and the conversation with the team, we agree that the tests I wrote about two years ago are too tightly coupled with the implementation.
This PR aims at refactoring these in order to have something more high-level, without caring too much of what's going on in the background.
=> Refactor fetching tests

CHANGES.rst, dirty_cat/datasets/_fetching.py, dirty_cat/datasets/tests/test_fetching.py
Reverts dirty-cat/dirty_cat#453
This will be reimplemented later
=> Revert "Support paths as strings in public fetching API"

.circleci/config.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/testing.yml
- Updates actions to newer versions
- Provide cleaner names
=> Ci improvements

CHANGES.rst, dirty_cat/datasets/_fetching.py, dirty_cat/datasets/tests/test_fetching.py
Reintroduces dirty-cat/dirty_cat#453
=> Support paths as strings in public fetching API

doc/conf.py
=> DOC Fix broken binder

dirty_cat/_fuzzy_join.py, dirty_cat/tests/test_fuzzy_join.py
=> FIX fuzzy_join AttributeError

.github/workflows/testing.yml
=> Fix CI not running tests

.github/workflows/testing.yml
=> Fix duplicate CI workers

dirty_cat/_fuzzy_join.py, dirty_cat/_similarity_encoder.py, dirty_cat/tests/test_fuzzy_join.py
Fix #533
and one small type of error change.
=> FIX Error when wrong type of fuzzy_join parameter

dirty_cat/_similarity_encoder.py
=> FIX _compute_drop_idx AttributeError with scikit-learn>=1.2.0

CHANGES.rst, dirty_cat/_fuzzy_join.py, dirty_cat/tests/test_fuzzy_join.py
=> ENH Add warning fuzzy join on missing values

doc/_static/stable_doc_redirect.js, doc/_templates/about.html, doc/conf.py
=> Dynamic stable link

build_tools/circle/push_doc.sh
Fix [deployment error](https://app.circleci.com/pipelines/github/skrub-data/skrub/1826/workflows/911d3dec-3239-46d8-be69-b906f905e091/jobs/3736) due to wrong link to repository
=> DOC Fix push_doc for website generation

.circleci/config.yml, .github/workflows/main.yml, .github/workflows/testing.yml
=> FIX Artifact not rendering

doc/conf.py, doc/index.rst
One last iteration over the landing page
=> Quick bootstrap

doc/about.rst, doc/documentation.rst, doc/encoding.rst
i am beginning a user guide. Will need more work, but I'm currently happy iterating fast to start giving a structure and online presence
=> Write some docs

examples/04_fuzzy_joining_and_FeatureAugmenter.py
Fix rendering error that slipped in with #514
=> DOC Fix fetching params

.github/workflows/testing.yml
Ref: https://github.com/skrub-data/skrub/pull/606
See [github actions documentation](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) for more details on matrix configurations.
=> [Fix] CI Strategy Matrix

CHANGES.rst, doc/cleaning.rst, doc/encoding.rst, examples/01_dirty_categories.py, examples/05_deduplication.py, skrub/_datetime_encoder.py
Looking at the log generated when building the documentation, I propose the following changes that should solve the issues.
=> DOC fix warnings issued by sphinx

doc/_static/css/custom.css, doc/_templates/index.html, doc/announcement.html
I really want to set the right expectations
I also added keywords (data wrangling, Python) for search engine optimization
=> DOC: add a large 'coming soon' note

doc/conf.py
=> Fix "edit on Github" button on website

doc/api.rst
=> STY: more vertical space on API docs

pyproject.toml, setup.cfg, skrub/_gap_encoder.py, skrub/_table_vectorizer.py, skrub/tests/test_deduplicate.py
or let's say almost all of them.
Unilke what we do in scikit-learn, this will also trigger locally, but I think it's a good thing.
=> CI Turn deprecation warnings into errors

skrub/_table_vectorizer.py, skrub/tests/test_table_vectorizer.py
Added raising an error for duplicate column names and a test.
=> added duplicate column names features

skrub/_table_vectorizer.py
(Sorry I think I messed up when applying a suggestion for #623 )
=> Typo: Remove double condition

examples/04_fuzzy_joining_and_FeatureAugmenter.py, skrub/datasets/_ken_embeddings.py, skrub/datasets/tests/test_fetching.py
Fix some broken links after #627 was fixed
=> FIX Broken links after dataset folder moved

examples/03_datetime_encoder.py
=> Rework `DatetimeEncoder` example

setup.cfg, skrub/datasets/_fetching.py
[Error raised here](https://app.circleci.com/pipelines/github/skrub-data/skrub/2603/workflows/792b4868-b714-4920-bf45-4806b8881ae3/jobs/5153)
=> FIX PosixPath object has no attribute 'startswith'

README.rst
***What this PR introduces?***
A light PR to improve the reading experience and onboarding of new users. The Friday sprint at EuroScipy was a good test for our README.
***What changes?***
- Rephrase some sentences to make them look more natural
- Update the EuroScipy poster with the one from 2023
- Various small add-ons and corrections
***Additional comments***
New contributors were eager to see the roadmap, but we can't share it directly since it is behind Inria's login wall.
=> Enhance README.rst

doc/vision.rst
=> DOC Fix few typos in `vision.rst`

examples/01_dirty_categories.py
Fix #704 
The second warning is still being investigated.
=> Remove warnings from 01_dirty_categories.py

examples/07_multiple_key_join.py
- Fixes rst
- Makes 07_multiple_key_join faster (addresses  #729 )
=> Faster example 07_multiple_key_join

CONTRIBUTING.rst
=> DOC Add instructions for documentation building

skrub/_similarity_encoder.py
=> FIX: Debugging the CI for window numpydoc error

skrub/_deduplicate.py
Partially closes https://github.com/skrub-data/skrub/issues/755
See https://github.com/skrub-data/skrub/pull/765
=> Fix flake8 noqa: `_deduplicate`

skrub/_fuzzy_join.py
Partially closes https://github.com/skrub-data/skrub/issues/755
See https://github.com/skrub-data/skrub/pull/765
=> Fix flake8 noqa: `_fuzzy_join`

.gitignore
Resolves https://github.com/skrub-data/skrub/issues/782
=> Add `doc/sg_execution_times.rst` to `.gitignore`

examples/02_investigating_dirty_categories.py
Towards https://github.com/skrub-data/skrub/issues/766
=> DOC Remove `filterwarnings` from `02_investigating_dirty_categories.py`

skrub/_table_vectorizer.py
The package is new, this no longer makes sense
=> MINOR: DOC: Remove versionadded

examples/04_fuzzy_joining.py, skrub/_fuzzy_join.py
Working towards #766
I have removed the warning thrown everytime fuzzy_join() is called. I have also got rid of the warnings.filterwarnings("ignore") in example 4. 
I got rid of the other changes
=> removed filter warnings and fuzzy join() experimental warning

examples/03_datetime_encoder.py
closes #799 
Reformatted the x labels on the graphs shown in photo. Let me know your thoughts
=> Reformatted x labels 

skrub/_table_vectorizer.py
Some fixes on the docstring of TableVectorizer following https://github.com/skrub-data/skrub/pull/814
=> DOC quick fixes for TableVectorizer

examples/01_encodings.py, skrub/_datetime_encoder.py, skrub/_gap_encoder.py, skrub/_minhash_encoder.py, skrub/_table_vectorizer.py, skrub/tests/test_datetime_encoder.py, skrub/tests/test_gap_encoder.py
Addresses https://github.com/skrub-data/skrub/issues/832
=> [FEAT] `get_feature_names_out` returns an array instead of a list

skrub/_gap_encoder.py, skrub/tests/test_gap_encoder.py
=> [MRG] FIX: GapEncoder get_feature_names_out on short words

.github/workflows/testing.yml, pyproject.toml, setup.cfg
fixes #846 
and adds a test ci job with python 3.12
=> add tests with python 3.12

skrub/_table_vectorizer.py, skrub/tests/test_table_vectorizer.py
=> do not cast datetimes to numpy

setup.cfg
Follow-up on https://github.com/skrub-data/skrub/pull/703 since the bug seems to have been addressed.
=> [MAINT] Replace Sphinx Gallery dev by stable

setup.cfg
avoid distributing eg the benchmarks
=> specify options.packages.find

skrub/_agg_joiner.py, skrub/_datetime_encoder.py, skrub/_fuzzy_join.py, skrub/_joiner.py, skrub/_table_vectorizer.py
I've added some backslashes for newlines, as well as a code block
I've renamed the joined colums from `_capitals` to `_right` in the `fuzzy_join` example because I think it's clearer, but I'm open to other names
=> [DOC] Multiple small improvements

skrub/_joiner.py, skrub/_utils.py
started appearing after latest pandas release
=> MAINT make sure pandas doesn't insert a "key_0" column in merge result

skrub/tests/test_sklearn.py
because refrenced pr has not been merged before 1.4
=> MAINT scikit-learn estimator check should not be run yet

skrub/_table_vectorizer.py, skrub/tests/test_table_vectorizer.py
Fixes some compatibilities issues with scikit-learn 1.4
=> MAINT compatibility for scikit-learn 1.4

README.rst
=> remove broken link from README

skrub/_dataframe/_common.py, skrub/_dataframe/tests/test_common.py
=> treat Nans as Nulls

skrub/_dataframe/_common.py, skrub/_dataframe/tests/test_common.py
otherwise pandas will try to align the indexes
=> reset_index on pandas series when making a dataframe

skrub/_dataframe/_pandas.py, skrub/_dataframe/_polars.py, skrub/_select_cols.py, skrub/tests/test_select_cols.py
small simplificaton of the implementation of `SelectCols` and `DropCols` that removes some duplicated code
=> use _selectors.select in SelectCols and DropCols

pixi.lock, pyproject.toml
This should fix `main` branch CIs build
=> MAINT require optional dependency to build the documentation

.github/workflows/run-code-format-checks.yaml
Use pixi for the pre-commit check
=> MAINT use pixi task for pre-commit CI

.github/dependabot.yml
This file should allow to check if we should update any of the GHA file and actions.
=> MAINT check if we should update the GHA yml file

examples/06_ken_embeddings.py
the example needs this small change after the bugfix in #956
=> FIX remove the unwanted suffix in example 6

skrub/_dataframe/_common.py, skrub/_dataframe/tests/test_common.py
a little helper needed for #945
=> add _dataframe.filter function

doc/encoding.rst, skrub/_tabular_learner.py
Those are comments that I wanted to raise regarding the documentation. There is nothing radical here. I just wanted to expand a bit the user guide by providing some information regarding the parameter of the `TableVectorizer`
=> DOC nitpicks on the documentation of `tabular_learner`

examples/01_encodings.py
My attention span is tiny. I need to fit everything on a screen to understand.
I removed a few lines / compressed the text to be able to see the important points quicker.
=> Simple start of the example

doc/encoding.rst, skrub/_tabular_learner.py, skrub/tests/test_tabular_learner.py
WIP: I'll wait for #962  to edit the documentation
=> add standard scaling to tabular_learner

CHANGES.rst, skrub/_joiner.py, skrub/tests/test_joiner.py
applies the tablevectorizer's preprocessing (cleaning string/object columns, parsing dates etc) to joining columns in the Joiner
=> ENH apply TableVectorizer processing on joining columsn of Joiner

doc/_templates/index.html
Add a `tabular_learner` example on the landing page
=> Add tabular_learner section

doc/conf.py
Finishing the work started in  #1004 : use the version configuration from main
=> DOC: use version.json from main

examples/00_getting_started.py, skrub/_reporting/_table_report.py
this adds links to
- a list of example reports: https://skrub-data.org/skrub-reports/examples/
- the toy/experimental pyodide demo: https://skrub-data.org/skrub-reports/index.html
=> add some links to the documentation

skrub/_interpolation_joiner.py, skrub/tests/test_interpolation_joiner.py
Follow-up after https://github.com/skrub-data/skrub/pull/1016
- Docstrings improvements
- Parametrize fixtures with `df_module`
- Relative imports in source, absolute imports in tests
- Some renaming and reordering of assignments
=> Format InterpolationJoiner

doc/conf.py, doc/version.json
for the banner: 
first let's fix the version numbers -- I got a bit ahead of myself with 1.3 
this is what happens when you do a release on friday night
=> fix version numbers

doc/_templates/index.html
Quick fix for https://github.com/skrub-data/skrub/issues/1040 and https://github.com/skrub-data/skrub/issues/1039
=> Add reference to links

doc/_templates/index.html
=> Fix reference links to home version 0.3.X

skrub/_reporting/_data/templates/report.js
jupyter notebooks capture arrow key events which prevents the report from seeing them and breaks using arrow keys to move to the next tab or sample table cell. this pr fixes this problem.
please give it a try on your preferred notebook-like environment if you use one and report where it breaks! we probably need to add some environments to the list that we detect and which trigger the special handling of keyboard events added by this pr
=> arrow key navigation in jupyter notebooks

.github/workflows/run-code-format-checks.yaml, .github/workflows/test-javascript.yml, .github/workflows/testing.yml, .github/workflows/update_pixi_lock_files.yml, pixi.lock
Bumping the version of `pixi` on the CI and update the lock files.
=> MAINT update the version of pixi to 0.30.0 and the lock files

CHANGES.rst, skrub/_agg_joiner.py, skrub/_dataframe/_pandas.py, skrub/tests/test_agg_joiner.py
Fixes #1019
The issue was Series didn't have a column name which resulted to None.
Presently its converting it to np array
=> Resolved : "AggTarget raises when y is a Series"

CHANGES.rst
after the 0.3.1 release this opens a new section for the changes of the next release in the changelog
=> open a new section in the changelog

pixi.lock, skrub/_dataframe/tests/test_common.py
closes #1128 
based on the skrub-bot branch to update the lock file; one test needs to be adjusted
=> update lock files

CHANGES.rst, skrub/_column_associations.py, skrub/tests/test_column_associations.py
=> fix column_associations failure on infinite values

CHANGES.rst
The changelog did not render right: https://skrub-data.org/stable/CHANGES.html
=> Fix small rst bugs

.github/workflows/testing.yml, pixi.lock, pyproject.toml
this updates the pyproject.toml pixi lock file and moves one of the CI jobs to 3.13
=> add python 3.13

doc/encoding.rst, examples/02_text_with_string_encoders.py, skrub/_gap_encoder.py, skrub/_minhash_encoder.py, skrub/_text_encoder.py
Small PR on top of https://github.com/skrub-data/skrub/pull/1159
* add see-also
* make the plot log yscale
* redo outline of encoding docs
=> String encoder minor changes

skrub/_reporting/_data/templates/_variables.css, skrub/_reporting/_data/templates/base.css
=> set link colors in tablereport

doc/_templates/index.html
As discussed: "Machine learning for dataframes"
=> New tagline on front page

CHANGES.rst, doc/reference/index.rst, examples/00_getting_started.py, skrub/__init__.py, skrub/_table_vectorizer.py, skrub/tests/test_table_vectorizer.py
Refactoring first, now I need to add the deprecation warning and add back SimpleCleaner as a subclass of Cleaner
=> Changing the name of SimpleCleaner to Cleaner

skrub/_column_associations.py
Fix formatting problems: https://skrub-data.org/stable/reference/generated/skrub.column_associations.html#skrub.column_associations
=> Fix rst in docstrings

pyproject.toml
This is mostly to have our new tagline, but I update a few names in the pyproject.toml
=> Update tagline (and a few names)

skrub/datasets/_ken_embeddings.py
=> Fix fetch_ken_table_aliases example rendering

doc/Makefile, doc/_static/css/custom.css, doc/_templates/index.html, doc/conf.py, doc/generate_pipeline_for_index.py, pyproject.toml, skrub/_expressions/_parallel_coord.py
Add a feature on the expressions on the front page
Fixes #1299
Adds quite a bit of engineering to generate the corresponding code snippets
=> [MRG] DOC: add expressions on front page

CHANGES.rst, examples/03_datetime_encoder.py, examples/04_fuzzy_joining.py, skrub/_table_vectorizer.py
Line too long was creating a warning.
But also, the "See also" title does not take a colon
=> Fix a malformated docstring

examples/expressions/10_expressions_intro.py, examples/expressions/11_expressions_explained.py, examples/expressions/12_scikit_learn_estimators_in_expressions.py, examples/expressions/13_choices.py, skrub/_expressions/_evaluation.py, skrub/_expressions/tests/test_errors.py
=> add notes about re-running notebook cells with side-effects

doc/generate_pipeline_for_index.py
Now that the name is optional, remove it
=> Make front page example simpler

skrub/_expressions/_estimator.py, skrub/_expressions/_skrub_namespace.py
TO CONSIDER: No tests that covers the lines that I changed
=> expressions cross_validate return DataFrame

examples/08_join_aggregation.py
as discussed in issue [1346](https://github.com/skrub-data/skrub/issues/1346), I update the hyperparameter tuning of HistGBT in the AggJoiner example
=> adjust hyperparameter tuning in 08_join_aggregation.py

CHANGES.rst, skrub/_expressions/_estimator.py, skrub/_expressions/_skrub_namespace.py, skrub/_expressions/tests/test_estimators.py, skrub/_expressions/tests/test_parallel_coord.py
=> Order in the parallel coordinate plot

skrub/_expressions/_estimator.py, skrub/_expressions/_parallel_coord.py, skrub/_expressions/tests/test_parallel_coord.py
Fixes https://github.com/skrub-data/skrub/issues/1380
=> Enable multi scoring for parallel plot

doc/cleaning.rst
Add to the narrative docs, to make it easier to find.
The cleaning functionality of skrub is quite light but 1) it was recently praised on linkedin, 2) this PR makes it easier for people to find functionality
=> Add cleaner to narrative docs

doc/version.json
Update the `doc/version.json` in the main branch.
=> MAINT update doc version in main branch

RELEASE_PROCESS.rst, doc/development.rst
Fixes https://github.com/skrub-data/skrub/issues/1391
Create a "Release Process" page accessible from the "Development" or "Contributing" guide.
=> More details on the release note

doc/documentation.rst, doc/selectors.rst, skrub/_select_cols.py
Fixes https://github.com/skrub-data/skrub/issues/1382
=> Add selector user guide

skrub/_expressions/_skrub_namespace.py
Addition of a line and missing point.
=> correct missing line and point (.)

doc/encoding.rst
=> Expand section on datetime encoding in user guide

doc/encoding.rst
Quick follow-up on https://github.com/skrub-data/skrub/pull/1450
=> Quick fix of the DatetimeEncoder user guide section

skrub/_reporting/_data/templates/dataframe-sample.css, skrub/_reporting/_data/templates/dataframe-sample.html
Follow-up on #1418, although I highly doubt a single user would have ever noticed this...
=> Fix some CSS in TableReport

skrub/_to_datetime.py
=> Fix ToDatetime import in docstring example #1471

examples/10_apply_on_cols.py
A missing change from https://github.com/skrub-data/skrub/pull/1478
=> add a variable to catch the pipeline

doc/api_reference.py
Fixes https://github.com/skrub-data/skrub/issues/1480
=> Move Cleaner and DropUninformative to the cleaner section

examples/data_ops/11_choices.py
change get_pipeline to make_learner in docs.
=> docs: update to new wording

skrub/_agg_joiner.py, skrub/_clean_categories.py, skrub/_clean_null_strings.py, skrub/_dataframe/_common.py, skrub/_dataframe/tests/test_common.py, skrub/_datetime_encoder.py, skrub/_dispatch.py, skrub/_join_utils.py, skrub/_reporting/_sample_table.py, skrub/_reporting/_utils.py, skrub/_to_datetime.py, skrub/selectors/_base.py
=> change _raise to _raise_dispatch_unregistered_type

skrub/_reporting/tests/test_table_report.py, skrub/tests/test_config.py
To start the issue https://github.com/skrub-data/skrub/issues/1655, and to unlock the PR https://github.com/skrub-data/skrub/pull/1654
=> chore: alleviate datasets downloads in test
