skrub-data/skrub

dirty_cat/similarity_encoder.py

The first option is not formatted correctly: https://dirty-cat.github.io/stable/generated/dirty_cat.SimilarityEncoder.html#dirty_cat.SimilarityEncoder
This patch is one way to solve it (although it looks a bit ugly in the source code)

DOC: formatting of the similarity options

---

dirty_cat/datasets/fetching.py

fixes #36 
response object does not implement __enter__
and __exit__ methods that are required when using 
a context manager (before mid 2017). 
so I used the wrapper contextlib.closing, which fixed the error.

context manager wrapper for earlier versions of request

---

dirty_cat/datasets/fetching.py

fixes #32
Even though this function is going to be removed soon, it is showing up in the sphinx main 
page, so it is better if the doc is not empty.

added docstring for fetch_employee_salaries

---

CHANGES.rst
dirty_cat/similarity_encoder.py
dirty_cat/test/test_similarity_encoder.py

Also increased the coverage a bit by adding a test about this feature (giving a list of categories to `SimilarityEncoder`).
The test relies on the `auto` behavior though, which may change, so @GaelVaroquaux if you are uncomforatable with it I can also simply check a hardcoded similarity matrix.

Fix error when list of categories

---

.travis.yml
CHANGES.rst
build_tools/circle/build_doc.sh
dirty_cat/similarity_encoder.py
dirty_cat/string_distances.py
dirty_cat/test/test_similarity_encoder.py
setup.py

Accelerate the computation in `SimilarityEncoder.transform` by:
* Parallelizing the similarity computations using `joblib`
* Computing the count vectors of the vocabulary at fitting time and not at transform time.

ENH accelerate ngram_similarity

---

build_tools/circle/build_doc.sh
dirty_cat/datasets/__init__.py
dirty_cat/datasets/fetching.py
dirty_cat/datasets/tests/test_fetching.py
dirty_cat/datasets/tests/utils.py
doc/conf.py
examples/05_scaling_non_linear_models.py

Example about non-linear starts stabilizing IMO, so I can start taking feedback. 
In short, the example shows a classification problem for the `traffic_violations` dataset.
5 types of models are implemented:
* `SimilarityEncoder` + `SVC`
* `SimilarityEncoder` + `RBFSampler` + `SVC`
* `SimilarityEncoder` + `RBFSampler` + `SGD`
* `SimilarityEncoder` fitted on a subset of the data + `RBFSampler` + `SGD`
* `SimilarityEncoder` fitted on a subset of the data  + `RBFSampler` + online `SGD`
Training set sizes still dummy to make CI pass fast. For now, the scripts takes around 15 sec to run.
`RBFSampler` can easily be switched in favor of `Nystroem`.

DOC first version of the non-linear online example

---

CHANGES.rst
dirty_cat/string_distances.py
dirty_cat/test/test_string_distances.py

Should resolve issue #115. There was 2 problems with our implementation of the Jaro and Jaro-Winkler distance.
- `search_range`, i.e. the maximum range when matching characters was different: `max_len // 2 -1` against `(min_len - 1) // 2`.
- In some cases like `min_len <= 3`, the Jaro-Winkler distance wasn't computed even though we set `winkler=True`.
I also added more thorough tests in `test_compare_implementations`. It should now discriminate implementations with different `search_range`.

Fixed dirty_cat jaro_winkler implementation to match Levensthein.

---

CHANGES.rst
dirty_cat/datasets/fetching.py
examples/01_investigating_dirty_categories.py
examples/02_fit_predict_plot_employee_salaries.py
examples/04_dimension_reduction_and_performance.py

Change the download source from official link to openML. 
For employees_salaries

[WIP] fix bug in examples

---

build_tools/circle/list_versions.py

The current version of `list_versions.py` is not able to make the doc for newer versions of scikit-learn (> 0.21), which prevents CircleCI from running `build_doc.sh`.
To fix that I have replaced `list_versions.py` with scikit-learn' own implementation: https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/circle/list_versions.py.

Fix list_versions.py to work on newer scikit-learn versions [doc build] 

---

examples/05_scaling_non_linear_models.py

There was some issue with example 05 that prevented CircleCI to build the doc with sphinx.
When performing online training on chunks of a dataframe, one of the chunks is empty after the preprocessing step and thus cannot be used for training. I simply added a test to check for empty chunks and skip iterations if needed.

Fix example 05 to check for empty chunks

---

dirty_cat/minhash_encoder.py
examples/02_fit_predict_plot_employee_salaries.py
examples/03_fit_predict_plot_midwest_survey.py

Fix #127  
In example 02, puting `n_components` = 300 gives results as good as one_hot_encoder (.85) but it take more time.
I put  `n_components` = 100 to have decent results.

Fix: Minhash encoder does not perform well on the dirty-cat examples

---

CHANGES.rst
dirty_cat/test/test_similarity_encoder.py
dirty_cat/test/test_target_encoder.py

Changes:
- Replaced sklearn's assert_raise_message() with pytest raises in target and similarity encoder.
- update to changes.rst for minhash handle_missing functionality.

replace sklearn assert function with pytest and changes.rst

---

.travis.yml

As requested by @GaelVaroquaux, migrated one worker from Python 3.7 to 3.8.
Linked with issue #136.

Migrating a Travis worker from Python 3.7 to 3.8

---

examples/04_dimension_reduction_and_performance.py

Added max_iter argument to the LogisticRegression instantiation in Notebook 04.
Solves "Warning messages in notebook 04_dimension_reduction_and_performance #140".
Source: https://stackoverflow.com/a/62113936
By the way, as mentioned in the answer:
> You may also standardize your data as the warning said, with `sklearn.preprocessing.scale()`.

Minor modification to avoid ConvergenceWarnings in Notebook 04.

---

.github/workflows/main.yml

Closes #111
This should be the equivalent to what I've done for nilearn.

Add github action artifact link redirector

---

.circleci/config.yml
examples/05_scaling_non_linear_models.py

CircleCI checks didn't pass after the last PR. When building example 05 in the documentation, an import error is raised when executing `from sklearn.linear_model.stochastic_gradient import SGDClassifier`. Since sklearn 0.22, it should be imported with `from sklearn.linear_model import SGDClassifier`instead, so I changed that line of code.
However I wonder why this error wasn't raised before. Maybe when merging PR to master, CircleCI doesn't build examples that weren't modified.

Fix CircleCI checks [doc build]

---

CHANGES.rst
dirty_cat/gap_encoder.py
dirty_cat/test/test_gap_encoder.py
dirty_cat/utils.py
doc/conf.py
doc/index.rst
examples/03_automatic_preprocessing_with_the_supervectorizer.py

Add 2D matrices support for GapEncoder

---

CHANGES.rst
requirements-min.txt
setup.py

Necessary for #155 and #200
Approved by @GaelVaroquaux

Bump minimal requirement for sklearn from 0.20.0 to 0.21.0

---

CHANGES.rst

For `pip install`, it's `--pre`, not `-pre`

Typo in CHANGES.rst

---

examples/06_dimension_reduction_and_performance.py

As pointed out in #155, there is a memory leak responsible for the CI errors.
This commit should lower the used memory of notebook 6 from ~1.3 GB to ~200 MB (measured with `tracemalloc` and `memory_profiler`), as well as making the build a little faster.

Fix memory leak in notebook 6

---

README.rst

This is a minor proposal for modernizing the README:
- Added the dirty_cat logo
- Added 5 badges (with https://shields.io):
- Supported Python versions (pulled from PyPi)
- Current release version on PyPi
- Monthly PyPi downloads
- Code coverage
- CircleCI status for `master`
- Modified the scikit-learn minimal dependency, should have been changed with #202 
See https://github.com/LilianBoulard/dirty_cat/tree/modernize_readme for the render
Inspired from [scikit-learn's README](https://github.com/scikit-learn/scikit-learn/blob/main/README.rst)

Modernize README

---

CHANGES.rst
dirty_cat/super_vectorizer.py
dirty_cat/test/test_super_vectorizer.py

Uses pandas [`TextParser`](https://github.com/pandas-dev/pandas/blob/06d230151e6f18fdb8139d09abf539867a8cd481/pandas/io/parsers/readers.py#L1289) (used in `read_csv`, as per @GaelVaroquaux suggestion in #234) instead of `convert_dtypes` in the SuperVectorizer `_auto_cast` method. This has several advantages:
- Type detection works on string columns, e.g `["3", "2", "1"]` would get detected as integer. Solves #234 
-  Missing values encoded as strings get treated as missing values, and don't prevent type detection. For instance,` [1, 2, "", 4]` is detected as integers. (solves  #231). Which strings get detected as Nans is easy to change (see below).
- Datetime columns are converted to datetimes, and the format is inferred by Pandas. Solve the first part of #233.
Some comments:
- TODO: I'd …

Change auto_cast in SuperVectorizer

---

CHANGES.rst
dirty_cat/gap_encoder.py
dirty_cat/test/test_gap_encoder.py

Thanks to @GaelVaroquaux, we noticed that the output of the gap encoder was identical when the parameter analyzer = "word" or  analyzer = "char". This is not possible as the encoding method should be different.
A test was added to test_gap_encoder.py to ensure that this is no longer possible.
Line 580 was missing the analyzer parameter which created the problem of identical outputs.
Finally, the Hashing Vectorizor on line 864 didn't take into account the change of the analyzer parameter, but always stayed "char", is this normal?
Thanks!

Added test of analyzer and corrected the gap encoder options

---

dirty_cat/gap_encoder.py
dirty_cat/super_vectorizer.py
dirty_cat/test/test_gap_encoder.py
dirty_cat/test/test_super_vectorizer.py
examples/03_feature_interpretation_gap_encoder.py

get_feature_names -> get_feature_names_out

Follow scikit-learn API change

---

dirty_cat/super_vectorizer.py

Following our discussion in #244.
I added text in the docs of the SuperVectorizer, to explain the meaning of the sparse_threshold parameter. 
As agreed, I just copied the same from the [Column Transformer](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html).
Thanks.

Doc threshold

---

dirty_cat/similarity_encoder.py

Hi,
I noticed that the [SimilarityEncoder documentation on the website](https://dirty-cat.github.io/stable/generated/dirty_cat.SimilarityEncoder.html#dirty_cat.SimilarityEncoder) is taking over some documentation from the methods it uses.
For instance, for the fit_transform function, we can read:  "Fit OneHotEncoder to X, then transform X.".
For user experience, I think it is better for the encoder to have it's own docs, so I added the fit_transform method with a simple doc copied from scikit-learn's [TransformerMixin](https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html).
What do you think?
Thanks

Improving SimilarityEncoder docs

---

CHANGES.rst
dirty_cat/super_vectorizer.py

Continuation of #216 
Fixes #259 by performing the same version check as the other occurrences.

Fix SuperVectorizer's `get_feature_names_out` `FutureWarning`

---

CHANGES.rst
dirty_cat/super_vectorizer.py

Solves #232 
Following discussion with @GaelVaroquaux in previous PR (#236), I've made the modification in the fit method of the SuperVectorizer.

Display column names instead of indices for remainder columns in the transformers_ attribute of the SuperVectorizer

---

doc/index.rst

For a congress I recently participated in, I realized a video presenting some encoders implemented in dirty_cat.
The video [is available on YouTube](https://youtu.be/_GNaaeEI2tg) and I though we could add it to the website if you think this is relevant :)

Add introductory video on the website

---

dirty_cat/similarity_encoder.py

I was fixing up some tests as part of #277, and they failed when using `get_feature_names_out` on the `SimilarityEncoder`.
After a bit of digging, this is due to a missing variable `n_features_in_`, that is [set in the `_fit` method](https://github.com/scikit-learn/scikit-learn/blob/8a8d0687eed25481db39aa5c5b85148b2933d0a7/sklearn/preprocessing/_encoders.py#L86) of the `_BaseEncoder` (from which the `OneHotEncoder`, and therefore, the `SimilarityEncoder` inherit).
We don't use this method, which is why it's not set.

Adapt the `SimilarityEncoder` to use `get_feature_names_out`

---

CHANGES.rst
README.rst
requirements-min.txt

This is a change extracted from #287: it aims at fixing the very slow CI for the minimal dependencies worker.
As these changes were already discussed over there, and this is an issue we have on all PRs right now, I'll merge these changes right away.

Bump scipy & numpy versions to fix the slow CI

---

dirty_cat/datasets/fetching.py
dirty_cat/datasets/tests/test_fetching.py

Trying to use the no-loading version of the fetchers, I realized we're not passing the target name, and it's annoying to hard-code in downstream code, so I've added it to the `DatasetInfoOnly` requirements.
Also, since we're now in Python 3.8+ territory, I've figured we should use dataclasses instead of namedtuples, as their syntax is a little nicer (though more verbose), but most importantly, they integrate type hinting !

Fetching: move `namedtuples` to `dataclasses`, and add target name to `DatasetInfoOnly`

---

CHANGES.rst
README.rst
benchmarks/similarity_scores_time_benchmark.py
build_tools/circle/build_doc.sh
dirty_cat/similarity_encoder.py
dirty_cat/string_distances.py
dirty_cat/test/test_similarity_encoder.py
dirty_cat/test/test_string_distances.py
examples/01_dirty_categories.py
examples/02_investigating_dirty_categories.py
examples/05_scaling_non_linear_models.py
examples/06_dimension_reduction_and_performance.py

Drop support for Jaro, Jaro-Winkler and Levenshtein distances

---

benchmarks/encoders_time_memory_bench.py

Hi,
I noticed there were no benchmarks that compare the different dirty_cat encoders. 
Inspired from [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/benchmarks/bench_text_vectorizers.py), this is a simple benchmark comparing time and memory usage of the Similarity, MinHash and Gap Encoder using the SuperVectorizer.
Main takeaways are :
- the MinHash is extremely fast compared to the other two encoding methods (5-10 times faster, depending on data);
- memory usage for MinHash and Gap Encoder are equivalent (but the second one is slower);
- memory usage of Similarity is much higher (around 2 times higher than the other two methods, as expected).
Thanks.

Add benchmark comparing encoders time and memory usage

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

Fixes https://github.com/dirty-cat/dirty_cat/issues/304.
This adds a simple pre-commit setup with `black`, `flake8`, `isort` and `mypy`.
Note that the code-base needs to be formatted using this setup.
IMO, this might better be done in another PR with a single commit to better ignore formatting changes (see [this blog](https://michaelheap.com/git-ignore-rev/) post for introduction).
Also, a GitHub action workflow can then be introduced to check that changes made in Pull Requests comply with this setup.

DEV Add a simple `pre-commit` setup

---

.github/workflows/run-code-format-checks.yaml
.pre-commit-config.yaml

Follow-up of #308.
This also remove mypy checks from pre-commit setup which creates confusion with version parsing via the private `Version` class.

CI Add GitHub action to run pre-commit checks 

---

dirty_cat/__init__.py
dirty_cat/datasets/__init__.py
dirty_cat/datasets/fetching.py
dirty_cat/datasets/tests/test_fetching.py
dirty_cat/datasets/tests/test_utils.py
dirty_cat/datasets/utils.py
dirty_cat/datetime_encoder.py
dirty_cat/fast_hash.py
dirty_cat/gap_encoder.py
dirty_cat/minhash_encoder.py
dirty_cat/similarity_encoder.py
dirty_cat/string_distances.py
dirty_cat/super_vectorizer.py
dirty_cat/target_encoder.py
dirty_cat/test/test_datetime_encoder.py
dirty_cat/test/test_fast_hash.py
dirty_cat/test/test_gap_encoder.py
dirty_cat/test/test_minhash_encoder.py
dirty_cat/test/test_similarity_encoder.py
dirty_cat/test/test_sklearn.py
dirty_cat/test/test_string_distances.py
dirty_cat/test/test_super_vectorizer.py
dirty_cat/test/test_target_encoder.py
dirty_cat/test/test_utils.py
dirty_cat/utils.py

Follow-up of #308 and #317.
This applies the `pre-commit` formatting on the whole code-base
A few docstrings lines were exceeding the column limit but we're hardly breakable. I chose to put a `# noqa` directive so that black ignore them; but there might be a better solution (such as defining custom types and using them in the docstring if it makes sense).
A follow-up PR will add a `.git-blame-ignore-revs` file not to have the formatting disrupt `git blame` with some documentation to have it setup, see [scikit-learn's](https://github.com/scikit-learn/scikit-learn/blob/main/.git-blame-ignore-revs).

MAINT Format the code-base to be `pre-commit` compliant

---

.git-blame-ignore-revs
README.rst

This comes as a follow-up of #314.
It adds a badge on the `README` to indicate that dirty_cat uses black.
It introduces .git-blame-ignore-revs, which contains a list of commits to be ignore via `git blame`. 
This file can be set as the default ignore file for blame by running the following command:
```bash
git config blame.ignoreRevsFile .git-blame-ignore-revs
```

DEV Ignore black code formating in `git blame`

---

doc/_static/custom.css

With the latest sphinx, there is an issue with repeated semicolons:
This PR is solving this issue by editing the CSS file.

DOC fix repeated semicolon

---

.coveragerc
dirty_cat/_fast_hash.py
dirty_cat/_test/test_fast_hash.py
dirty_cat/_test/test_gap_encoder.py
dirty_cat/_test/test_minhash_encoder.py
dirty_cat/_test/test_super_vectorizer.py
dirty_cat/datasets/_tests/test_fetching.py

closes #334 
Remove the `if __name__ == "main"` from the tests and module files since it is not required.
I let the one in the benchmark since they can be used with `python my_bench.py`.

MAINT remove if __name__ == 'main'

---

dirty_cat/tests/test_docstrings.py

Thanks to a comment on the numpydoc meta issue, I've noticed that the file `dirty_cat/tests/test_docstrings.py` was empty in master.
A bisect identified the #331 as the culprit, which is now obvious given the +/- diff.
I've reintroduced the file, which is not necessarily the best solution (a cherrypick might have been a better one, but I have next to no experience with it).

Restore test_docstrings.py

---

.circleci/config.yml
build_tools/circle/build_doc.sh
build_tools/circle/push_doc.sh

Fixes #393.
As discussed over there, it seems some occurrences of `master` were not renamed and which causes the generated doc to not be pushed to the website repo.
I didn't because I wasn't sure what the environment variables were (e.g. `CIRCLE_BRANCH`). Should've checked :p
https://circleci.com/docs/built-in-environment-variables/

Fix generated doc push to website

---

doc/_static/custom.css
doc/_templates/about.html
doc/conf.py

Fixes #361
Adds a warning banner in the "about" section, which is the left panel on the website page.
It has the advantage of being visible wherever you are on the website, and as it's the only big red thing on the screen, it's pretty noticeable, so that should do the trick.
Adding it to page RST (for example in `class.rst`) was a hustle, so I ended up dropping this idea.

Add warning banner on development documentation

---

dirty_cat/_similarity_encoder.py

Small fix. 
As `get_feature_names` will be deprecated, it's best to use directly `get_feature_names_out` in the small example.

DOC Replace get_feature_names by get_feature_names_out

---

README.rst

Small fix.
Spotted a missing link in the new version of the README 
This is because we deleted `min_requirements.txt` in the meantime.

DOC Fix readme

---

dirty_cat/_super_vectorizer.py

The bug appeared because on newer versions of sklearn, ColumnTransformer has no attribute get_features_names. With the existing code, this meant that we used the non-transformed columns names. I've changed the logic to just distinguish if we call get_features_names or get_feature_name_out based on sklearn version.

fix bug on get_features_out from SuperVectorizer with new sklearn versions

---

dirty_cat/_datetime_encoder.py
dirty_cat/_gap_encoder.py
dirty_cat/_similarity_encoder.py
dirty_cat/_target_encoder.py
dirty_cat/_utils.py
dirty_cat/tests/test_super_vectorizer.py

Because ``np.array`` is a function, and ``np.ndarray`` is the class.

Replace np.array with np.ndarray in type hints

---

build_tools/circle/build_doc.sh

Fix #447 
Using the fix from https://github.com/ContinuumIO/anaconda-issues/issues/13110 works. What I'm not sure is why it only appeared now.
Once this is merged, tests on failing PRs should be relaunched.

fix circleCI doc building

---

doc/conf.py

Currently, page titles are rendered with the code ``&mdash`` in the title, which is very ugly.
The dash is already rendered by sphinx or whatnot, so we should remove it.

Fix em dash in website titles

---

dirty_cat/_gap_encoder.py
dirty_cat/tests/test_gap_encoder.py

Solves #474
Previously, an error was raised from Kmeans, and talked about `n_clusters` instead of `n_components`.

More informative error when n_samples < n_components in GapEncoder

---

doc/_static/custom.css

Better layout on mobile phones
Should avoid the dangling list on the left, and the dangling "example" on the bottom right

DOC: css for narrow screens

---

build_tools/circle/build_doc.sh

Fixes #490 
The error is due to the way the path is interpreted when executing `chmod +x miniconda.sh && bash ./miniconda.sh -b -p $MINICONDA_PATH`: `$MINICONDA_PATH` is `"~/miniconda"`, which should be resolved to `/home/circleci/miniconda`. Instead, it is resolved as `/home/circleci/~/miniconda`. The next line, `export PATH="$MINICONDA_PATH/bin:$PATH"`, interprets the tilde correctly, and thus tries to find `/home/circleci/miniconda`, which doesn't exist.
To solve that, I've hardcoded the directory name `miniconda`, which is created in the same directory as `miniconda.sh`.
Please let us know if there is any drawback with this approach!

Fix CI issue

---

dirty_cat/_similarity_encoder.py

When instantiating the `SimilarityEncoder`, it raises a warning by default, which is bad behavior.
```
>>> SimilarityEncoder()
UserWarning: The "similarity" argument is deprecated since dirty_cat 0.3, and will be removed in 0.5.The n-gram similarity is the only one currently supported.
```

Set default value to None for similarity in SimilarityEncoder

---

CHANGES.rst
dirty_cat/_table_vectorizer.py
dirty_cat/tests/test_table_vectorizer.py
examples/01_dirty_categories.py
examples/03_datetime_encoder.py

Change default `low_card_cat_transformer` in SuperVectorizer to use handle_unknown="ignore".
Solves #455

Use handle_unknown=ignore in SuperVectorizer

---

build_tools/github/test.sh
dirty_cat/tests/test_minhash_encoder.py
setup.cfg

Adds [`pytest-xdist`](https://github.com/pytest-dev/pytest-xdist) to the development dependencies to parallelize the tests, thus speeding them up.

Parallelize parametrized tests

---

build_tools/github/install.sh
setup.cfg

On some versions specified in the CI matrix, the installation of dirty_cat takes more than 10 minutes, which is very annoying and consumes resources pointlessly.
This PR attempts to fix that.

Fix long CI install

---

CHANGES.rst
dirty_cat/_fuzzy_join.py
dirty_cat/tests/test_fuzzy_join.py

ENH fuzzy_join takes missing values into account as in pandas.merge

---

dirty_cat/_feature_augmenter.py

**What does this implement/fix?**
Not all typo requires PRs, but since this one is easy to spot and is located on the first parameter of `FeatureAugmenter`, I thought it was necessary :)

DOC `FeatureAugmenter` typo quick fix

---

doc/conf.py

Fix #527
Since #507 `"filename_pattern": ""` was removed so this reverted to the default sphinx-gallery behaviour which is to run the examples starting with `plot_`. I used `".*"` to match any kind of files which is a bit more explicit than `""`, you could also use `\d+_.*\.py` or a variation of it if you prefer.
Locally this work, but I am going to push a commit with `[doc build]` to make sure that examples are indeed run.

DOC Configure filename_pattern to run all examples during doc build

---

examples/01_dirty_categories.py

**What does this implement/fix?**
- Fix a formatting error in the documentation of `01_dirty_categories`
- Replace `# %%` with `#### ...` to stick with the global cell separator style of the dirty_cat examples.
***What we had***
***What this PR introduces***
- I also removed the "The learning pipeline" header, since it was a bit redundant with the "Assembling a machine-learning pipeline that encodes the data". WDYT?

DOC clean formatting for `01_dirty_categories`

---

dirty_cat/_similarity_encoder.py

In sklearn's `OneHotEncoder`, `_compute_drop_idx()` was replaced by `_set_drop_idx()` in V1.2.2 (see https://github.com/scikit-learn/scikit-learn/commit/1380e3c09b46568cd536ebc6f4720388f2f763d5), but we use it from V1.2.0, causing a bug on sklearn's versions 1.2.0 and 1.2.1. This PR fixes this.

Fix _set_drop_idx bug for sklearn versions >=1.2.0 and < 1.2.2

---

examples/04_fuzzy_joining_and_FeatureAugmenter.py

**What does this implement/fix?**
The `04_fuzzy_joining_and_FeatureAugmenter` example uses a `print_worst_matches` function to sort a DataFrame, while the same result could be obtained with a much more simple `df.sort_values`.

DOC simplify `print_worst_matches` for `04_fuzzy_joining_and_FeatureAugmenter`

---

CHANGES.rst
dirty_cat/datasets/__init__.py
dirty_cat/datasets/_ken_embeddings.py
dirty_cat/datasets/tests/test_ken_embeddings.py
examples/06_ken_embeddings_example.py

Add functions for exploring KEN embeddings

---

CHANGES.rst
dirty_cat/_gap_encoder.py
dirty_cat/tests/test_gap_encoder.py

Don't continue fitting in `GapEncoder.transform`

---

.github/workflows/main.yml

I've noticed that since #545 was merged, the artifacts (doc) do not render.
This is necessary for reviewing #551.
I've noticed updates on the [github action repository](https://github.com/larsoner/circleci-artifacts-redirector-action), which might be the reason why it's not working anymore.

Fix CircleCI artifacts not rendering

---

CHANGES.rst
skrub/_table_vectorizer.py
skrub/tests/test_table_vectorizer.py

Fix #555 
We now fall back on `pandas.to_datetime` format inference when we don't find a format with `_infer_datetime_format`. Indeed, this function relies on pandas' `guess_datetime_format`, which doesn't work for weirder date format, and `pandas.to_datetime` uses `dateutil` when `guess_datetime_format` doesn't work.
The code to catch warnings could maybe be simplified.

fall back to pandas if no datetime format is found

---

skrub/_minhash_encoder.py

the `MinHashEncoder` works for data with multiple columns, but the documentation doesn't reflect this.

Fix X shape in minhash_encoder docstrings

---

CHANGES.rst
skrub/_gap_encoder.py

Implements parallelization of the `GapEncoder` column-wise, as it is currently a simple for loop.
This could speed up the process significantly for wide datasets (intuitively, to be benchmarked).

Parallelize the `GapEncoder`

---

.circleci/config.yml
build_tools/circle/build_doc.sh

I saw that in the documentation that you have an extra colon in the docstring:
Indeed, this is due to the version of `sphinx` and `docutils` used: https://github.com/sphinx-doc/sphinx/issues/10594
This has been solved in the new sphinx version but I assume that using Python 3.9 is locking the version of `sphinx` used. Just wanted to give it a try to bump from 3.9 to 3.10.
Alternatively, one can overwrite the CSS most probably with something like:
```css
dl.field-list  .colon {
display: none;
}
```
However, it would be easier to just fix it by installing a more recent sphinx version. FYI, we use sphinx 6.0.0 in scikit-learn.

MAINT bump python version to 3.10

---

.github/workflows/testing.yml
CHANGES.rst
pyproject.toml
setup.cfg

Currently, we only want as users people who are early adopters and quite agile.
I'm in favor of dropping support for Python versions earlier than 3.10. If nothing else, it will make our build matrix lighter.

MAINT: bump to Python 3.10

---

.github/ISSUE_TEMPLATE/doc_improvement.yml
.github/workflows/changelog.yml

Two things that bug me:
- The tag `No Changelog Needed` is title-cased, while the other tags are lowercase
- When we submit a fix for the CI, no changelog entry is required
This PR fixes that.

Normalize tags

---

CHANGES.rst
examples/01_dirty_categories.py
examples/04_fuzzy_joining_and_FeatureAugmenter.py
setup.cfg
skrub/_datetime_encoder.py
skrub/_gap_encoder.py
skrub/_similarity_encoder.py
skrub/_table_vectorizer.py
skrub/_utils.py
skrub/tests/test_gap_encoder.py
skrub/tests/test_similarity_encoder.py
skrub/tests/test_table_vectorizer.py

Bump the minimal versions of all dependencies and removes the requirement on `requests` (we don't use directly).
For numpy, scipy and pandas, versions date back to mid/late 2022, and scikit-learn 1.2.1 was released in January.

Bump requirements

---

CHANGES.rst
skrub/_minhash_encoder.py
skrub/tests/test_minhash_encoder.py

We generate feature names as `feature_name_1_0`, ... `feature_name_1_n_components` etc. If feature names are missing, we use `x_0`, `x_1` etc
(+ a test to check that the MinHashEncoder is deterministic)

add get_feature_names_out to MinHashEncoder

---

CHANGES.rst
skrub/_similarity_encoder.py
skrub/tests/test_similarity_encoder.py

Fix #138
The fuzzy_join and the GapEncoder have the same parameter, it may be useful in the SimilarityEncoder as well.

FEA Add analyzer parameter to SimilarityEncoder

---

skrub/_datetime_encoder.py
skrub/_deduplicate.py
skrub/_fast_hash.py
skrub/_fuzzy_join.py
skrub/_gap_encoder.py
skrub/_minhash_encoder.py
skrub/_similarity_encoder.py
skrub/_string_distances.py
skrub/_table_vectorizer.py
skrub/_target_encoder.py
skrub/_utils.py
skrub/tests/utils.py

Following #613, we can now use the modern type hints provided by numpy to document array-likes and n-D arrays!

Use modern numpy type hints

---

.github/workflows/testing.yml
build_tools/github/install.sh

Setup a cron job to test against nightly dependencies. It can also be manually triggered with `[deps nightly]` in the commit message.

MAINT Test against nightly dependencies

---

CHANGES.rst
skrub/_datetime_encoder.py
skrub/_deduplicate.py
skrub/_fast_hash.py
skrub/_fuzzy_join.py
skrub/_gap_encoder.py
skrub/_minhash_encoder.py
skrub/_similarity_encoder.py
skrub/_string_distances.py
skrub/_table_vectorizer.py
skrub/_target_encoder.py
skrub/_utils.py
skrub/tests/test_table_vectorizer.py
skrub/tests/utils.py

Fix #622, which was due to mixed types column.

convert mixed column types to string

---

CHANGES.rst
skrub/_deduplicate.py
skrub/datasets/_generating.py
skrub/tests/test_deduplicate.py

FEA Parallelize deduplicate function

---

CHANGES.rst
skrub/_table_vectorizer.py

which means that the output is always dense. I don't know which is better between this and a small value (like 0.01 or 0.05). Right now it is 0.3, which means that a simple pipeline TableVectorizer-->HistGradientBoostingClassifier often breaks when experimenting.

change default sparse_threshold to 0 in TableVectorizer

---

.github/workflows/changelog.yml

Follow-up of https://github.com/skrub-data/skrub/pull/612
The check changelog workflow is broken. Even when the label `no changelog needed` is set, the workflow still runs. See https://github.com/skrub-data/skrub/pull/649 for example.

CI Fix check changelog

---

CHANGES.rst
skrub/_table_vectorizer.py
skrub/tests/test_table_vectorizer.py

Prevent `TableVectorizer` from failing if there are missing values in a categorical column

---

skrub/tests/test_deduplicate.py

`test_backend_respected` from `test_deduplicate` is randomly failing when `make_deduplication_data` doesn't generate enough variation (#673), which breaks the CI. This PR sets the random_state of `make_deduplication_data` to prevent the failure.

Fix randomly failing deduplicate test

---

skrub/_check_dependencies.py

currently check_dependencies fails when scikit-learn=1.4.0.dev0 for instance.
The fix is to include prereleases in the version check, as documented here
https://packaging.pypa.io/en/stable/specifiers.html#packaging.specifiers.Specifier.contains

FIX check_dependencies takes prereleases into account

---

CHANGES.rst
benchmarks/bench_fuzzy_join_sparse_vs_dense.py
benchmarks/utils/join.py
skrub/datasets/_fetching.py
skrub/datasets/_utils.py
skrub/datasets/tests/test_fetching.py
skrub/datasets/tests/test_utils.py

Closes #641
- Add a `get_data_home` function that returns the root data directory path, and create it if it does not already exist. By default, it is set to `~/skrub_data`.
- Modify the `get_data_dir` function that returns the data directory where a given loader stores data. The output directory is a subdirectory of the root data directory.
- Implement tests for these two functions.

Move default location of data to the user home folder

---

CHANGES.rst
skrub/_table_vectorizer.py
skrub/tests/test_table_vectorizer.py

Make sure to clone `remainder` when it is a transformer such that this is not an instance shared across transformers.
This test is highly relevant for https://github.com/skrub-data/skrub/pull/675

FIX make sure to clone remainder in TableVectorizer

---

doc/install.rst

docs(install): add '' around pip install -e .[dev] (#695)

---

examples/03_datetime_encoder.py

Fix the [Circle CI error](https://app.circleci.com/pipelines/github/skrub-data/skrub/2616/workflows/081cb0aa-c49d-493e-be10-514619e3ad1b/jobs/5167) from PR #680
***What changes***
Remove the duplicate line:
```
.. |TimeSeriesSplit| replace::
:class:`~sklearn.model_selection.TimeSeriesSplit`
```
In the substitute name definition of our example 3.

TimeSeriesSplit definition in example 3 is duplicated

---

skrub/datasets/_generating.py

PR #700 experienced what seems to be [a rare error](https://github.com/skrub-data/skrub/actions/runs/5928122276/job/16073058088?pr=700) from a non-deterministic function, making the test unstable.
***What changes***
Replace np.random.choice with the random state provided in input to make the test stable.
***Additional comments***
This rare error might mean the deduplicate function returns unexpected results when the problem is ill-conditioned. This instability will need further investigation.

Use RandomState rng instead of np.random in `make_duplicate()`

---

examples/03_datetime_encoder.py

Fixes https://github.com/skrub-data/skrub/issues/716
***What changes***
A typo at the top of the `03_datetime_encoder.py` file generated an error during sphinx tree parsing. We had the following warning when building the doc:
```
doc/auto_examples/03_datetime_encoder.rst:21: WARNING: malformed hyperlink target.
```
Removing the typo seems to make the example accessible again.

DOC Fix url page missing in our example 3

---

README.rst

Fix https://github.com/skrub-data/skrub/issues/624
***What changes***
The centering directive needed a line break with the badges to render. After doing that, the rendering wasn't even centered, so I removed the directive entirely.

Fix Badges on README.rst

---

setup.cfg
skrub/__init__.py

A solution to #698, which fixes the regression introduced in #648
***What changes?***
- Add 'packaging' to the requirements in setup.cfg
- ~Slightly change the warning message to make it more explicit~ remove the warning message

Add "packaging" as a requirement

---

skrub/_table_vectorizer.py

**Reference**
Fix a breaking change introduced in scikit-learn private method `ColumnTransformer._iter` by https://github.com/scikit-learn/scikit-learn/pull/27005 at https://github.com/scikit-learn/scikit-learn/pull/27005/files#diff-fea489154c629a45ec01030d191f20465e809124a24260ac35fb884bc855140fR365.
**What changes**
Add keyword arguments when calling _iter within the `TableVectorizer.get_feature_names_out` method.
**Aditionnal comments**
I wonder how sustainable this is and if there's a way to avoid relying on this private method.

Fix TableVectorizer `get_feature_names_out`

---

skrub/_minhash_encoder.py

**References**
Addresses https://github.com/skrub-data/skrub/issues/704
**What changes**
https://github.com/skrub-data/skrub/pull/647 introduced a warning upon running the `transform` method from `MinHashEncoder`. This is due to `check_input(X)` returning a numpy array, which we pass to `self._check_feature_names`. This latter method raises a warning because it's expecting a Pandas DataFrame.
**Alternative solutions**
Remove `_check_feature_names` entirely, but I wouldn't recommend that.
**Additionnal comment**
Overall, I'm concerned that skrub is becoming increasingly more coupled with scikit-learn private methods. Changes made to these private methods (like https://github.com/skrub-data/skrub/pull/722, even though https://github.com/skrub-data/skrub/pull/675 is an attempt to decouple …

MAINT Fix `feature_name` warning during `transform` for `MinHashEncoder`

---

skrub/_fuzzy_join.py

**Reference**
Fix https://github.com/skrub-data/skrub/issues/691
**What does this PR implement?***
Pandas is deprecated setting values to columns of different types. In particular, setting np.nan across columns that are not float is deprecated.
We now need to [convert the dataframe to nullable dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html#pandas.DataFrame.convert_dtypes), accepting pd.NA as values.

MAINT Fix pandas nightly

---

.github/workflows/testing.yml
CHANGES.rst
build_tools/github/install.sh
doc/api.rst
setup.cfg
skrub/_utils.py
skrub/dataframe/__init__.py
skrub/dataframe/_namespace.py
skrub/dataframe/_pandas.py
skrub/dataframe/_polars.py
skrub/dataframe/_types.py
skrub/dataframe/tests/test_namespace.py
skrub/dataframe/tests/test_pandas.py
skrub/dataframe/tests/test_polars.py

**References**
This PR aims at simplifying #600 by adding the `dataframe._pandas` and `dataframe._polars` namespaces prior to it.
It also enables solving issues like https://github.com/skrub-data/skrub/issues/730.
This PR takes into account the latest reviews made in #600.
**What does this PR implement?**
- Create a new submodule `skrub.dataframe` so that the `join` and `aggregate` functions for Pandas and Polars can be shared more easily across skrub.
- Add the `get_df_namespace` function and the `DataFrameLike`, `SeriesLike` types in separate files within `skrub.dataframe`.
- Add a specific documentation entry in the API section for the pandas and polars submodules.
**Additional comments**
This PR doesn't take into account the output of the discussion …

FEAT Add `aggregate` and `join` functions for Pandas and Polars

---

skrub/_table_vectorizer.py
skrub/tests/test_table_vectorizer.py

**References**
Addresses https://github.com/skrub-data/skrub/issues/679
**What does this PR implement?** 
`TableVectorizer` currently doesn't support sparse matrices. Until then, we should also prevent users from using Pandas sparse arrays.
This PR suggests that, during the `_check_input` call, we iterate on dataframe columns to look for the "sparse" accessor. We raise an error when at least one column is sparse.
**Alternative solution**
AFAIK, there is no way to identify a sparse column within a Pandas dataframe without iterating on the columns.
cc @LeoGrin

MAIN Improve the error message for Pandas sparse arrays in TableVectorizer

---

CHANGES.rst
skrub/_datetime_encoder.py
skrub/tests/test_datetime_encoder.py

- Fix #741 Remove millisecond extraction in DatetimeEncoder (Turns out you pandas' `DatetimeIndex` don't have a `millisecond` attribute.)
- Fix #745 Stop using the `floor` function and simplify the logic to check if we need `total_time`
- Close #744 Adds a `None` option for `extract_until` to only extract `total_time`.
@jeromedockes

DatetimeEncoder fixes

---

skrub/_minhash_encoder.py

Partially closes https://github.com/skrub-data/skrub/issues/755
See https://github.com/skrub-data/skrub/pull/765

Fix flake8 noqa: `_minhash_encoder`

---

skrub/_datetime_encoder.py

Partially closes https://github.com/skrub-data/skrub/issues/755
Formatting col_names like this: "my_col"
And parameters in code blocks like this: ``X``

 Fix flake8 noqa: `_datetime_encoder`

---

doc/conf.py

When building the doc, many terms are highlighted, even though they don't link to anything in particular. This happens in the parameters and returns type hinting of docstrings
For example below, you can see that "of", "or", and "optional" are in purple:
I'm proposing to disable this like so:
I've added a line in `doc/conf.py` that tells numpydoc to ignore all unrecognized terms. More info here: https://numpydoc.readthedocs.io/en/latest/install.html
---------
Another before/after example:

DOC Ignore unrecognized types in docstrings

---

examples/03_datetime_encoder.py

Towards #766
Also there is generated file `doc/sg_execution_times.rst` which isn't in .gitignore, if that makes sense to add it there I can do it here or in separate PR.

DOC Remove `filterwarnings` from `03_datetime_encoder.py`

---

doc/conf.py

This PR sets the icon of the browser tab.
- Current:
- New:

DOC - set the browser tab icon 

---

CHANGES.rst
doc/api.rst
doc/assembling.rst
examples/04_fuzzy_joining.py
skrub/__init__.py
skrub/_select_cols.py
skrub/dataframe/_pandas.py
skrub/dataframe/_polars.py
skrub/tests/test_select_cols.py

closes #670 
a decision on the API has actually not been made in the linked issue, this is to help make the discussion more concrete

[MRG] Add `SelectCols(cols)` and `DropCols(cols)` transformers

---

build_tools/github/test.sh

the problem was introduced in #797  because the added line `coverage xml` exits with code 0

ensure test.sh exits with status 0 if tests fail

---

doc/_static/css/custom.css

The search result page is currently justified on the right as shown in the figure below.
Reproduce that by typing in text on the search bar.
- Before
- After
- remove justify-content property (checked it has no side-effects)
- fix the format and syntax of ``custom.css``

DOC - fix layout of search results page 

---

skrub/_datetime_encoder.py
skrub/tests/test_datetime_encoder.py

**Reference**
Follows-up on https://github.com/skrub-data/skrub/pull/784
**What does this PR implement?**
- Heterogeneous arrays containing arbitrary objects like sets raise TypeErrors. This PR fixes these by catching TypeError, which allows returning the input.
- Heterogeneous arrays containing datetimes objects like `pd.Timestamp` and `datetime.datetime` also raise errors, because Pandas' `guess_datetime_format` only accepts string values. We now skip the call to `guess_datetime_format`  by ensuring the input array is invariant under `astype(str)` transformation.
Before:
```python
import pandas as pd
from skrub import to_datetime
to_datetime([pd.Timestamp("2019-01-01"), "yo"])
to_datetime([pd.Timestamp("2019-01-01"), "2020-01-01"])
to_datetime(['2020-01-01', {'hello'}])
```
After: …

[ENH] make `to_datetime` more robust to bad inputs

---

skrub/_dataframe/_pandas.py
skrub/_dataframe/_polars.py
skrub/_dataframe/tests/test_pandas.py
skrub/_dataframe/tests/test_polars.py
skrub/_datetime_encoder.py
skrub/tests/test_datetime_encoder.py

**What does this PR address?**
`to_datetime` converts every dataframe's column into a list of vectors using `to_numpy()` for every column. This results in the loss of extension dtypes (e.g.,`pd.Int64Dtype`) and categorical dtypes since we recreate the original dataframe from this mapping of numpy 1d arrays.
- This PR suggests a simple **temporary** workaround that casts back to their original types all columns that are not parsed as datetime. In the future, we need to stop converting series with `to_numpy()` and specialize the datetime parsing logic for Pandas and Polars. We will remove this workaround then.
- It also extends the `make_series` and `make_dataframe` methods to accept dtypes argument.
Before
```python
import pandas as pd
from skrub import to_datetime …
```

[MAIN] Preserve extension dtypes and categorical dtypes in `to_datetime`

---

README.rst

Hi, small change to add a link to the JupyterCon 2023 talk to the README, it fits with the other resources we link to :)

Add JupyterCon talk link

---

skrub/_datetime_encoder.py
skrub/tests/test_datetime_encoder.py

**Reference**
Fix a bug introduced in https://github.com/skrub-data/skrub/pull/828, which is currently [breaking the CI](https://app.circleci.com/pipelines/github/skrub-data/skrub/3132/workflows/821474d3-18dc-48d7-96d4-66392715d2b3/jobs/6139).
**What does this PR implement?**
- This PR suggests avoiding calling `_is_column_datetime_parsable` when the input is already of numeric or datetime data type, as initially proposed by Jérome https://github.com/skrub-data/skrub/pull/823#discussion_r1392726786.
- It also adds tests for `to_datetime`

[FIX] Hotfix `to_datetime` for timezone

---

skrub/_datetime_encoder.py
skrub/tests/test_datetime_encoder.py

**Reference**
This PR addresses https://github.com/skrub-data/skrub/issues/835
**What does this PR implement?**
- Sample 10 rows to infer the datetime format instead of using the whole array, yielding a 500x speed up on a 1d array of size 100k.
- Add some tests using 20 different `random_state`

[MAIN] Accelerate guess datetime format

---

skrub/_deduplicate.py

Towards https://github.com/skrub-data/skrub/discussions/843
- This PR replaces the `data` parameter of `skrub._deduplicate.deduplicate` with `X`.
- It suggests few nitpicks in the documentation of `deduplicate` as well.

[MAINT] Harmonize deduplicate input name

---

doc/_templates/index.html

The encoding and gap_encoder example links on the homepage are currently broken.

Fix the homepage example links

---

skrub/_fuzzy_join.py
skrub/_joiner.py
skrub/tests/test_joiner.py

Locally, these tests and docstrings were flaky because the distances in the k-NN search where equals.
Find a new example without any tie.

MAINT avoid tie breaking in joiner examples

---

skrub/_dataframe/_common.py
skrub/_similarity_encoder.py
skrub/datasets/_fetching.py

in the scikit-learn main branch `parse_version` is not in `utils` anymore but can still be imported from `utils.fixes`

MNT import parse_version from sklearn.utils.fixes

---

skrub/conftest.py

when using pytest -v with this change the tests that use this fixture will look like
```
skrub/_dataframe/tests/test_common.py::test_unique[pandas] PASSED                                                                                                                                  
skrub/_dataframe/tests/test_common.py::test_unique[polars] PASSED 
```
instead of 
```
skrub/_dataframe/tests/test_common.py::test_unique[df_module0] PASSED                                                                                                                                  
skrub/_dataframe/tests/test_common.py::test_unique[df_module1] PASSED 
```

parametrize with keys so we get more informative test names

---

skrub/_dataframe/_test_utils.py
skrub/tests/test_joiner.py

The goal of this PR is to uniformize how we write tests: 
- to take advantage of `dispatch` for comparing dataframes with a custom implementation of `assert_frame_equal`,
- to avoid the boilerplate 
```
import pandas as pd
MODULES = [pd]
ASSERT_TUPLES = [(pd, assert_frame_equal)]
if POLARS_SETUP:
import polars as pl
from polars.testing import assert_frame_equal as assert_frame_equal_pl
MODULES.append(pl)
ASSERT_TUPLES.append((pl, assert_frame_equal_pl))
```
in each test module, by using the `df_module` fixture in `conftest` instead.
I propose to use `df_module` to parametrize tests and create the dataframes (when we wouldn't have access to a dataframe to feed as a first parameter of a dispatched function), and to use functions in `_dataframe._common` and `_test_utils` for all other …

Use dispatch and module fixture in tests

---

skrub/datasets/tests/test_ken_embeddings.py

A quick fix for #900 (which should remain open until the downloads and test are actually improved and the skip is removed)

temporarily skip ken embedding download tests

---

benchmarks/bench_gap_divergence.py
benchmarks/bench_gap_es_score.py
skrub/_gap_encoder.py

From the top of the head, we should always have the mixins on the left of `BaseEstimator` for the MRO to work properly (e.g. for tags inheritance).
Quick fix to solve issues that I let pass in a previous PR.

FIX make sure to have Mixin on the left of BaseEstimator

---

examples/06_ken_embeddings.py

this example needs to be updated now MinHash is a single-column transformer.
I'm not sure why CircleCI did not fail in the original PR. anyway here is the fix

Fix example 6

---

skrub/_check_input.py
skrub/_clean_categories.py
skrub/_clean_null_strings.py
skrub/_dataframe/_common.py
skrub/_datetime_encoder.py
skrub/_dispatch.py
skrub/_selectors/_base.py
skrub/_to_datetime.py

- Uniformize `df`, `col`, `obj` arguments in dispatched functions
- Specify `argument_type` when applicable

[MAINT] Harmonize parameter names in private helpers: col, df & specify argument_type in dispatched .specialize

---

skrub/_dataframe/_common.py
skrub/_dataframe/tests/test_common.py
skrub/_on_each_column.py
skrub/_on_subframe.py
skrub/_utils.py
skrub/tests/test_table_vectorizer.py

I think this may be a better option than #940 
when the input is a polars dataframe and the transformer given to OnEachColumn or OnSubFrame is a scikit-learn transformer which exposes the `set_output` API, we would like to call `set_output(transform='polars')` so that it returns us a polars dataframe.
However, in scikit-learn < 1.3, the 'polars' option is not available, only 'pandas'.
so we have a few options:
- force scikit-learn >= 1.4 but that is quite constraining for users because it is very recent
- basically re-implement set_output ourselves, which is not good because it duplicates code that is already in scikit-learn 
- use `set_output(transform='pandas')` and convert the result to `polars` with `polars.from_pandas`. This lets scikit-learn deal with the conversion from numpy, …

FIX handle polars transformer output in scikit-learn < 1.4

---

CHANGES.rst
skrub/datasets/_ken_embeddings.py
skrub/datasets/tests/test_ken_embeddings.py

When `pca_components=None`, the parameter `suffix` was disregarded in `fetch_ken_embeddings`.
This PR fixes this bug and add a non-regression test.

FIX always take into account suffix parameter in fetch_ken_embeddings

---

skrub/_tabular_learner.py

Small nitpicks where I would like to require all arguments apart from `estimator` to be keyword only. It would allow us to introduce any new parameter in the future without caring that our user was passing by position or not.
It is removing the future hassle questioning if we should put a new parameter or not of the signature.

FIX use keyword-only argument

---

skrub/_gap_encoder.py
skrub/tests/test_gap_encoder.py

handling missing values is actually handled in the computation of unique values now, with the addition of `unique_strings` so passing a custom preprocessor is not necessary and anyway it works for None and pd.NA but not for numpy nan

remove _preprocess_text which is not necessary

---

skrub/datasets/_fetching.py
skrub/datasets/tests/test_fetching.py

this test if causing the CI to fail due to a download error. here also, (as for the ken embeddings) the real fix is to mock doownloads in tests but in the meanwhile this allows the ci to run @glemaitre

MAINT xfail the fetch_movielens test

---

skrub/_utils.py
skrub/tests/test_on_each_column.py

oneachcolumn and onsubframe want dataframe output from their transformers. if the method exists, they call `set_output` on the transformer so that scikit-learn transformers produce dataframe output. however `set_output` may fail in cases where the output would be correct anyway, eg a Pipeline containing transformers that produce dataframes by default but not exposing a `set_output` method.
this pr allows `set_output` to fail and still attempts the transformation -- the type of the output is checked in any case

ENH allow set_output to fail

---

skrub/_on_each_column.py

closes #976 
the error now shows how to use single-column transformers such as the `GapEncoder` in the `ColumnTransformer`

more details about the ColumnTransformer in error message

---

skrub/_gap_encoder.py
skrub/tests/test_gap_encoder.py

fixes a regression introduced when the GapEncoderColumn was made the GapEncoder: appending column numbers to topic names was not done correctly anymore

FIX deduplication of gapencoder output columns

---

pyproject.toml

this avoids having the version in 2 places (VERSION.txt and pyproject.toml) and thus the risk to forget updating one of them

MAINT make version and readme dynamic fields in pyproject.toml

---

CHANGES.rst
doc/_static/css/custom.css
doc/_templates/index.html
doc/about.rst
doc/conf.py
doc/development.rst
doc/documentation.rst
doc/index.rst

This PR will:
- move the development page to its own section to have the user guide only about the library tools
- add the changelog out of the development page
- remove the left sidebar when there is no item to click on
- add a title to the index page
- remove the footer on the page. We should probably make it more visible to get access to the changelog and contributing guideline.

DOC reorganize a bit user guide structure

---

doc/_templates/numpydoc_docstring.rst

This should solve the issue having the attributes appearing after the examples.

DOC reorder properly the numpydoc docstring

---

doc/conf.py

the default sphinx gallery thumbnail for examples without a plot is faded out giving the impression that something went wrong or something is missing. But it's valid for an example not to create any matplotlib plots, for example example 0 getting started.
shall we consider replacing the default thumbnail with something else, like the skrub logo?

Set sphinx gallery default thumbnail?

---

doc/conf.py
doc/version.json

Add a version switcher to easily go from dev to stable.
For now, the version.json file points to this PR, but we will need to change it to point to main branch on skrub

DOC: Add version switcher

---

doc/conf.py

Removing the pypi button with no logo
before:
after:

Remove pypi button

---

skrub/_reporting/_data/templates/base.css

in the report we include the copy of normalize.css distributed with pure which provides some baseline default styling and makes stuff more similar across browsers.
one problem with it is it hides the browser's default highlighting of the element that has keyboard focus, this PR removes that rule

use browser default style for focus-visible

---

skrub/_reporting/_data/templates/base.css
skrub/_reporting/_data/templates/column-filters.html
skrub/_reporting/_data/templates/skrub-report.js
skrub/_reporting/js_tests/cypress/e2e/column-filters.cy.js

variant of #1010 : hide the select altogether instead of disabling it

hide column filter selector when in associations tab

---

CHANGES.rst
skrub/_agg_joiner.py
skrub/_multi_agg_joiner.py
skrub/tests/test_agg_joiner.py
skrub/tests/test_multi_agg_joiner.py

Fixes #1005 
this ensures that AggJoiner and AggTarget outputs always have the same names even in the presence of duplicated column names in the inputs

ensure aggjoiner & aggtarget have consistent output names

---

CHANGES.rst
skrub/_dataframe/_common.py
skrub/_dataframe/tests/test_common.py
skrub/_interpolation_joiner.py
skrub/_join_utils.py
skrub/tests/test_interpolation_join.py
skrub/tests/test_join_utils.py

Closes #897 
```
>>> import polars as pl
>>> from sklearn.neighbors import KNeighborsRegressor
>>> from skrub import InterpolationJoiner
>>> buildings = pl.DataFrame(
...     {"latitude": [1.0, 2.0], "longitude": [1.0, 2.0], "n_stories": [3, 7]}
... )
>>> annual_avg_temp = pl.DataFrame(
...     {
...         "latitude": [1.2, 0.9, 1.4, 1.7, 5.0],
...         "longitude": [0.8, 1.1, 1.8, 1.8, 5.0],
...         "avg_temp": [10.0, 11.0, 15.0, 16.0, 20.0],
...     }
... )
>>> joiner = InterpolationJoiner(
...     annual_avg_temp,
...     key=["latitude", "longitude"],
...     regressor=KNeighborsRegressor(2),
... )
>>> joiner.fit_transform(buildings)
┌──────────┬───────────┬───────────┬──────────┐
│ latitude ┆ longitude ┆ n_stories ┆ avg_temp │
│ ---      ┆ ---       ┆ ---       ┆ ---      │ …
```

ENH polars support for InterpolationJoiner

---

CHANGES.rst
skrub/_fuzzy_join.py
skrub/_join_utils.py
skrub/_joiner.py
skrub/tests/test_join_utils.py
skrub/tests/test_joiner.py

random (but consistent across calls to transform) strings are inserted in duplicate names to avoid errors.
This is to be consistent with the AggJoiner and AggTarget

Allow duplicate column names in Joiner

---

skrub/_reporting/_summarize.py

tiny detail: make sure the stream is flushed otherwise the last line may take longer to appear eg in ci logs

flush stdout after computing all column summaries

---

CHANGES.rst
skrub/_agg_joiner.py
skrub/_dataframe/_pandas.py
skrub/_dataframe/tests/test_pandas.py
skrub/tests/test_agg_joiner.py

ATM the AggJoiner and AggTarget when using value counts or histogram include an unwanted "index" column in their output.
After performing a groupby, the grouping column is in the index of the pandas result. to have it as a column and be able to join on it, we need to do a `reset_index`. `skrub._dataframe._pandas.aggregate` used to do it for histogram and value counts, but not for other aggregation functions. This went unnoticed/was not a problem because the aggjoiner and aggtarget used pandas.merge which then performed the merge on the index rather than a column, because it allows "right_on" to be either a column index or an index level index.
in #945 a `reset_index` was added, but in both for mean() and for value_counts(). So before the reset_index was done 0 times for mean(), 1 times …

no "index" column in aggtarget output

---

doc/conf.py

this doesn't really address #1029 but that looks like it will take a bit more time than expected.
in the meanwhile this makes jupyterlite get the latest version from pypi, which means that we have the right version on the stable documentation (without having to do 2 releases and update the url every time), which is already an improvement.

pip install skrub instead of full url

---

skrub/_reporting/_table_report.py

These are actually provided by methods now, but were never removed from the `Attributes` section of the docstring

Remove inexistant attributes from TableReport docstring

---

CHANGES.rst
skrub/_reporting/_data/templates/base.css
skrub/_reporting/_data/templates/copybutton.css
skrub/_reporting/_data/templates/standalone-report.css
skrub/_reporting/_data/templates/standalone-report.html

partly addresses #1037 
can be discussed in another pr:

Fonts in inline report

---

doc/_static/css/custom.css
doc/conf.py

Those are the necessary change to move the download link and binder/jupyterlite button on the left sidebar.

MAINT move sphinx gallery download and try buttons on the left side bar

---

skrub/_reporting/_associations.py
skrub/_reporting/_summarize.py
skrub/_reporting/tests/test_summarize.py

before we would show at most 20 but only those that have an association above 0.2
having 2 cutoffs was confusing: if usually there are 20 but on my data only 15 show up (even if I have many columns in the dataframe) it is not clear why
this pr always shows the top 20

always show top 20 associations regardless of their value

---

skrub/_reporting/_data/templates/dataframe-sample.css
skrub/_reporting/_data/templates/report.js

ATM the selected table cell is outlined in black. that's ok in firefox but that is the color used by chrome to draw the focus ring, so there it makes it look like the selected cell has the keyboard focus even when it doesn't.
This PR makes the outline dotted when the focus is outside of the table and makes sure the cell has the default focus ring when it is in it

Better distinguish focus & selection in sample table

---

doc/_templates/index.html

On another note, maybe "Create strong scikit-learn pipeline baselines effortlessly with TableVectorizer and tabular_learner" is a bit hard to read, WDYT ?

[DOC] Fix small typo in landing page

---

skrub/_reporting/_data/templates/dataframe-sample.css
skrub/_reporting/_data/templates/dataframe-sample.html
skrub/_reporting/_data/templates/icons/three-dots-vertical.svg

A tiny change to make ellided cells a bit more visible, as I find that the implementation in main can be understood as two different tables:
This PR:
Main:

Ellided cells a bit more visible

---

CONTRIBUTING.rst
doc/_static/css/custom.css
doc/install.rst

**Reference**: https://github.com/skrub-data/skrub/issues/1071
**What does this PR propose?**
- Clarifying the redirect from the contributing page to the "Install > From source" section. Note that clicking on the link on the current doc takes you to the pip section, not to the "From source" section.
- Adding the lint and test dependencies to the "From source" guideline
- Removing the table of contents at the beginning of the document, because:
- It is redundant: the info is displayed on the right panel
- It takes some vertical place
- It turns every header into a link, which is confusing, and brings you back to the table of contents on click (see [this comment](https://github.com/skrub-data/skrub/issues/1071#issuecomment-2349570135)).
- Mention Discord as a place to discuss and ask …

DOC Enhance the install and contributing sections

---

skrub/_reporting/_data/templates/buttons.html
skrub/_reporting/_data/templates/copybutton.css

the copy buttons stretch across the box they copy which is fine in the most common case of just 1 line but weird otherwise.
also @Vincent-Maladiere said it would be best to have them always visible and I agree
this pr also improves a bit the colors of default/hover/active states
**before**
**after**

align copy buttons to flex-start + always visible

---

CHANGES.rst
skrub/_dataframe/_common.py
skrub/_reporting/_data/templates/column-summary.html
skrub/_reporting/_html.py
skrub/_reporting/_plotting.py
skrub/_reporting/_summarize.py
skrub/_reporting/_utils.py
skrub/_reporting/tests/test_summarize.py
skrub/_reporting/tests/test_table_report.py

fix error when report input contains lists #1066

---

skrub/_reporting/_data/templates/report.js

in jupyter and vscode we make sure that the tablereport gets arrow key keydown events which are otherwise captured by the notebook or vscode.
this adds revealjs slides to the list where this is done

tablereport captures keydown events in reveal js (slides)

---

CHANGES.rst
skrub/_reporting/_data/templates/base.css
skrub/_reporting/_data/templates/report.js
skrub/_reporting/_data/templates/summary-statistics.css
skrub/_reporting/_data/templates/summary-statistics.html

The column containing the column name in the summary statistics tab panel sticks on the left of the table, so that when we scroll horizontally we can still see (the end of) the column names

make the 'column name' column always visible in summary stats table

---

CHANGES.rst
skrub/_reporting/_data/templates/dataframe-sample.html
skrub/_reporting/_data/templates/report.js
skrub/_reporting/js_tests/cypress/e2e/dataframe-sample.cy.js

currently before clicking on any of the cells it is not possible to bring focus to the sample table with the keyboard. this PR makes the table sequentially focusable (with Tab); when it receives focus it activates the first cell

make sample table sequentially focusable when no cell is active

---

skrub/_reporting/_data/templates/base.css

this is a small adjustment while we do not yet have a dark theme, it tells the browser to always use light-theme colors for the system ui elements (scrollbar etc). the reports are already usable regardless of the color scheme of the page and OS settings, this is just a cosmetic detail to avoid having a dark scrollbar on a light background eg in macos which looks weird

set color-scheme to only-light in table report

---

CHANGES.rst

as mentioned in this [comment](https://github.com/skrub-data/skrub/pull/1098#issuecomment-2387959764) a previous pr was missing a changelog entry
ATM the bot only complaines about the changelog if some tests have been modified, which causes a few false negatives. shall we make it check the changelog for all PRs, given that silencing false positives is easy with the "changelog not needed" label?

add missing changelog entry

---

CHANGES.rst
skrub/_reporting/_data/templates/column-filter.css
skrub/_reporting/_data/templates/column-filter.html
skrub/_reporting/_data/templates/tabs.css
skrub/_reporting/_html.py
skrub/_reporting/js_tests/cypress/e2e/column-filter.cy.js
skrub/_reporting/js_tests/cypress/e2e/column-summaries.cy.js
skrub/_reporting/js_tests/cypress/e2e/dataframe-sample.cy.js
skrub/_reporting/tests/test_table_report.py

reduces the width and height of the column filter in the tablereport. it is a little less obvious what it does now but the upside is there is a smaller chance that it needs to wrap to a different line than the tabs

make column filter select smaller in tablereport

---

CHANGES.rst
skrub/_reporting/_plotting.py
skrub/_reporting/tests/test_table_report.py

fixes #1111 
all nulls are dropped before building the histogram, they are never useful for this plot anyway

drop nulls before plotting histogram

---

CHANGES.rst
examples/00_getting_started.py
skrub/__init__.py
skrub/_reporting/__init__.py
skrub/_reporting/_patching.py
skrub/_reporting/_table_report.py
skrub/_reporting/tests/test_patch_display.py

With 
```python
skrub.patch_display()
```
the default HTML representations of pandas & polars dataframes are replaced with TableReports
it can be undone with
```python
skrub.unpatch_display()
```
`patch_display` can be called before or after importing the libraries (it will import them if they are installed but not imported yet. as this is only useful for interactive work I don't think it is a problem)
still need to add tests & an example but first I would like opinions on whether we actually want something like this or not
TODO:
[Example](https://output.circle-artifacts.com/output/job/88bb3835-6978-4982-b198-bafef2e78783/artifacts/0/doc/auto_examples/00_getting_started.html#generating-an-interactive-report-for-a-dataframe)

add functions to patch the _repr_html_ of pandas & polars dataframes

---

doc/reference/generating_a_report.rst

As well as the corresponding function unpatch_display
This is important also to get to work all the ":func:" references (including those added automatically to the docs)

DOC: Add patch_display to the API docs

---

CHANGES.rst
skrub/_utils.py
skrub/tests/test_on_each_column.py

OnEachColumn, when its transformer is a scikit-learn transformer exposing set_output, calls set_output('pandas') or set_output('polars') to get the output in the correct dataframe.
in old scikit-learn versions, set_output('polars') is not supported, so OnEachColumn does set_output('pandas') and later does the conversion itself with `polars.from_pandas`.
or at least it's supposed to -- when doing a small change in #973 to handle possible exceptions raised by set_output I forgot to copy the "else" part of the "if scikit-learn < 1.4" block so now it is always using "polars" even in scikit-learn versions that don't support it.
this pr fixes the regression

fix regression with set_output in scikit-learn < 1.4

---

CHANGES.rst
doc/reference/generating_a_report.rst
skrub/__init__.py
skrub/_column_associations.py
skrub/_reporting/_summarize.py
skrub/_reporting/tests/test_summarize.py
skrub/tests/test_column_associations.py

adds `column_associations` (the function that computes the pairwise cramer v stats shown in the tablereport) as a function accessible in the public api

add column_associations public function

---

examples/00_getting_started.py

Follow-up to #1116 
Fixing example now that we don't split columns by type in `AggJoiner` anymore

Fix getting started example

---

CHANGES.rst
examples/08_join_aggregation.py
skrub/_reporting/_data/templates/buttons.html
skrub/_reporting/_data/templates/column-summary.html
skrub/_reporting/_data/templates/report.html
skrub/_reporting/_data/templates/report.js

The way the computation of the correct viewbox for the plots is done currently is slow when there are many columns.
This makes all the bounding box computation in one go with no changes to the document in between to avoid unnecessary recomputations of the styles and layout
also as it adds a few functions to the report code, now is a good time to put it in a module to avoid polluting the global namespace so this PR adds that too

Faster svg viewbox computation in tablereport

---

CHANGES.rst
skrub/_reporting/_plotting.py
skrub/_reporting/tests/test_table_report.py

fixes #1134 
this is a quick fix for #1134 
later we can improve handling of infinite or very large values by
- excluding them from the computation of summary statistics (?)
- excluding them while setting the bounds of the shown histograms to avoid unhelpful histograms with only one bar
however this requires taking care to make sure that the user realizes those outliers have been discarded so may take a bit more discussion. So I suggest we avoid crashing for now so that the release 0.3.2 does not depend on solving these more subtle choices

fix histogram plot failure on float('inf')

---

CHANGES.rst
skrub/_reporting/_summarize.py
skrub/_reporting/js_tests/cypress/e2e/summary-statistics.cy.js
skrub/_reporting/tests/test_summarize.py

fixes #1070 
ATM the tablereport only computes the number of unique values for categorical columns.
with this pr it does it for all columns

compute n_unique for all columns in tablereport

---

CHANGES.rst
skrub/_column_associations.py
skrub/_dataframe/_common.py
skrub/_dataframe/tests/test_common.py
skrub/_reporting/_data/templates/column-summary.html
skrub/_reporting/_plotting.py
skrub/_reporting/_summarize.py
skrub/_reporting/_utils.py
skrub/_reporting/tests/test_summarize.py
skrub/_reporting/tests/test_table_report.py
skrub/_reporting/tests/test_utils.py

fixes #1132 
this converts the duration/timedelta columns to numeric so we get a histogram & summary statistics rather than a bar plot
durations and datetimes are also converted to numeric for the column associations detection
the choice of time unit & conversion could probably be improved but this is already better than treating them as categorical

better handling of timedelta in tablereport

---

skrub/_reporting/README.rst
skrub/_reporting/_table_report.py

_represention_ is now _representation_.
_pacakges_ is now _packages_.

fix: Correct typo in TableReport docstring

---

CHANGES.rst
skrub/_reporting/_patching.py
skrub/_reporting/tests/test_patch_display.py

add verbose parameter to print_display to  toggle on or off printing of progress messages when generating table report

---

skrub/_column_associations.py

add example for Cramer V
Will be rendered here in documentation:  
https://skrub-data.org/stable/reference/generated/skrub.column_associations.html
Towards #1181

DOC add example for Cramer V for column_associations

---

CHANGES.rst
skrub/_tabular_learner.py
skrub/tests/test_tabular_learner.py

closes #1177 
Adding "regression" as an alias to "regressor" and "classification" to "classifier"

ENH adding alias "regression" and "classification" 

---

CHANGES.rst
skrub/_reporting/_plotting.py

fixes #1171
matplotlib.rc_context seems to prevent the inline display of plots in jupyter notebooks in some cases
this removes the use of this context manager
the context manager does not seem to do anything fancier than the try/finally statement in this PR, but the difference is here we only set the key we are interested in `svg.fonttype` whereas upon exit `rc_context` updates all params except the backend:
https://github.com/matplotlib/matplotlib/blob/v3.9.3/lib/matplotlib/__init__.py#L1142-L1196

remove use of matplotlib.rc_context

---

CHANGES.rst
skrub/_reporting/_utils.py
skrub/_reporting/tests/test_utils.py

FIX better display of object columns with multi-line repr in tablereport

---

README.rst

While I like the idea of showcasing the tablereport as soon as possible because it is one of the more visual and immediatly understood features, I think we were too quick in adding that gif to the readme:
- I'm not sure if it is due to the large size (most likely) or how the link is generated from markdown but it does not display on PyPI's "description" page
- the `figure` directive renders as a link so clicking on the image downloads the gif which nobody wants to do
- having a largish animation that moves a lot and we cannot stop can be distracting or even disagreeable for some
this is a quick fix to revert the change and then we can discuss some more what should be in the readme and maybe reduce it further to drive everyone to the home page instead

revert gif in the readme

---

doc/announcement.html
doc/conf.py

As discussed, removing the banner mentioning that the API is subject to change without notice

[DOC] Remove API change banner on landing page

---

.gitignore

Fix #1209 
This small PR adds `.venv` and `env_skrub` in the `.gitignore`, as `env_skrub` is the env name suggested in the contributing guide and `.venv` is often used IMO

Add `.venv` and `env_skrub` in the `.gitignore`

---

skrub/_reporting/_data/templates/report.js

This PR tries to enhance how the report detects vscode theme.
It should address the issue with high contrast theme discovered [here](https://github.com/skrub-data/skrub/pull/1228#issuecomment-2630589233).
Here is what I get now in high contrast:

enh: vscode theme detection

---

skrub/_reporting/_data/templates/report.js

I wonder if looking at the text color on the report's parent element and trying to choose the most appropriate theme based on the result would be a good heuristic (when the other heuristics we have for vscode & jupyter notebook don't give a result), or if it is better to fall back on the system preference as we currently do...
this detects for example when the user set the theme in the skrub online documentation manually by clicking the button, to something different than their system or browser default. But I don't know if this is something that happens in practice; I guess dark theme users will have it set at the OS level?
@rouk1  WDYT?

try to guess the appropriate color theme based on parent element's color

---

CHANGES.rst
skrub/_reporting/_summarize.py
skrub/_reporting/_table_report.py
skrub/_reporting/tests/test_patch_display.py
skrub/_reporting/tests/test_table_report.py

Write table report  progress messages to stderr

---

CHANGES.rst
skrub/_string_encoder.py
skrub/tests/test_string_encoder.py

For memory and speed:
- Significant memory improvement (I did not measure)
- 1.5 speedup on one task

ENH: optimize StringEncoder

---

CHANGES.rst
doc/end_to_end_pipeline.rst
skrub/_tabular_learner.py
skrub/tests/test_tabular_learner.py

This PR adds periodic encoding by default when the estimator is a linear model

ENH add periodic encoding in tabular learner

---

examples/01_encodings.py

This PR addresses Issue #1268 by correcting the `xerr` parameter in the horizontal bar plot within the "Encoding: from a dataframe to a numerical matrix for machine learning" example. The standard deviations of feature importances are now properly assigned to `xerr`, ensuring accurate representation of error bars.

Fix error bars plotting in encoding example

---

.github/workflows/testing.yml
CHANGES.rst
skrub/_reporting/_data/templates/_variables.css
skrub/_reporting/_data/templates/base.css
skrub/_reporting/_data/templates/buttons.html
skrub/_reporting/_data/templates/column-summaries.html
skrub/_reporting/_data/templates/report.js
skrub/_reporting/_patching.py
skrub/_reporting/_summarize.py
skrub/_reporting/_table_report.py
skrub/_reporting/tests/test_patch_display.py
skrub/_reporting/tests/test_table_report.py

Skip Plotting in Table Report Based on Max Columns Given

---

examples/expressions/13_choices.py
skrub/_expressions/_choosing.py
skrub/_expressions/_estimator.py
skrub/_expressions/_evaluation.py
skrub/_expressions/_expressions.py
skrub/_expressions/_inspection.py
skrub/_expressions/_parallel_coord.py
skrub/_expressions/_skrub_namespace.py
skrub/_expressions/tests/test_choosing.py
skrub/_expressions/tests/test_estimators.py
skrub/_expressions/tests/test_evaluation.py
skrub/_expressions/tests/test_inspection.py
skrub/_expressions/tests/test_parallel_coord.py

closes #1311 
The `name` parameter of all choices is now optional. When displaying results if there is no name the slightly shortened repr of the choice is used:
```
>>> from sklearn.datasets import make_classification
>>> from sklearn.preprocessing import StandardScaler
>>> from sklearn.linear_model import LogisticRegression
>>> from sklearn.ensemble import RandomForestClassifier
>>> import skrub
>>> X, y = make_classification()
>>> search = (
...     skrub.X(X)
...     .skb.apply(StandardScaler(with_mean=skrub.choose_bool()))
...     .skb.apply(
...         skrub.choose_from(
...             {
...                 "logistic": LogisticRegression(
...                     C=skrub.choose_float(0.1, 10.0, log=True),
...                     fit_intercept=skrub.choose_bool(),
... …
```

make the choice name optional

---

skrub/_expressions/_estimator.py
skrub/_expressions/_expressions.py
skrub/_expressions/_skrub_namespace.py
skrub/_expressions/_utils.py
skrub/_expressions/tests/test_errors.py
skrub/_expressions/tests/test_estimators.py

use cloudpickle to serialize expressions held in an estimator + skip eager pickling checks

---

skrub/_expressions/_expressions.py
skrub/_expressions/tests/test_errors.py

There is a check that sees if a function called in an expression returns None as this probably indicates it modifies its input in-place instead of returning a new value. When it was decided it should emit a warning rather than raise an exception I forgot to add the return statement after removing the raise statement

fix missing return

---

skrub/_expressions/_evaluation.py
skrub/_expressions/_expressions.py

this allows ExprImpl subclasses to define `eval` to override how they are evaluated. it simplifies things a bit by not needing to special case expressions that may not need all their children to be evaluated (eg an applied estimator does not need y for predict, if_else needs only one of the branches to be evaluated, ...)

Small refactoring in expressions evaluation

---

CHANGES.rst
doc/reference/index.rst
examples/08_join_aggregation.py
examples/FIXME/08_join_aggregation_full.py
skrub/__init__.py
skrub/_agg_joiner.py
skrub/_dataframe/tests/test_common.py
skrub/_expressions/_expressions.py
skrub/_fuzzy_join.py
skrub/_interpolation_joiner.py
skrub/_join_utils.py
skrub/_joiner.py
skrub/_on_each_column.py
skrub/_on_subframe.py
skrub/_reporting/_html.py
skrub/_select_cols.py
skrub/_table_vectorizer.py
skrub/_to_datetime.py
skrub/_wrap_transformer.py
skrub/selectors/__init__.py
skrub/selectors/_base.py
skrub/selectors/_selectors.py
skrub/selectors/tests/test_base.py
skrub/selectors/tests/test_selectors.py
skrub/tests/test_datetime_encoder.py
skrub/tests/test_fuzzy_join.py
skrub/tests/test_on_each_column.py
skrub/tests/test_on_subframe.py
skrub/tests/test_wrap_transformer.py

closes #1146 
It is already exposed as a public attribute of skrub as they can be used with expressions so 
```python
from skrub import selectors as s
```
already works on the main branch
however the actual module is called `_selectors` so 
```python
import skrub.selectors
```
raises an importerror
this pr renames it to `selectors`

Make the selectors module public

---

skrub/__init__.py
skrub/_expressions/__init__.py
skrub/_expressions/_estimator.py

as it is redundant with `Expr.skb.train_test_split`

remove skrub.train_test_split

---

skrub/_expressions/_skrub_namespace.py

Small typo fix + cross link to sklearn

Small typo in `skb.get_randomized_search` docstring

---

.github/workflows/testing.yml
doc/skrub_pipeline.rst
pyproject.toml

This adds the prompts recognized by doctest in the user guide section about expressions.
The main advantage is that we can check the code runs and produces the expected output with pytest so there is less chance that it becomes outdated.
also users are probably used to seeing such snippets (eg in the reference documentation, scikit-learn user guide, ...) so it might make it slightly easier to immediately recognize the code and the outputs
also adds a step in the tests CI workflow to run those doctests

use doctests in skrub pipeline user guide

---

examples/expressions/11_choices.py
skrub/_expressions/_choosing.py
skrub/_expressions/_evaluation.py
skrub/_expressions/_skrub_namespace.py
skrub/_expressions/_utils.py
skrub/_expressions/tests/test_choosing.py
skrub/_expressions/tests/test_inspection.py

~Not sure if we want this~, but we discussed it once or twice with @Vincent-Maladiere : allowing to specify an explicit default value for the choices.
This PR adds a new parameter `default`. If provided, it is used in the default pipeline. It does not affect the parameter grid so for example it has no effect on the behavior of `.skb.get_randomized_search()` and `.skb.get_grid_search()`.
```
>>> import skrub
Normally the default is the middle of the range
>>> skrub.choose_float(0.0, 10.0).as_expr().skb.eval()
np.float64(5.0)
But we can provide our own default value instead
>>> e = skrub.choose_float(0.0, 10.0, name='c', default=2.0).as_expr()
>>> e.skb.eval()
2.0
>>> e.skb.get_pipeline().fit_transform({})
2.0
The param grid and hyperparameter search don't change
>>> …
```

Add  a `default` parameter to choices

---

doc/documentation.rst
doc/skrub_pipeline_validation.rst
examples/expressions/11_choices.py

this adds a user guide page to cover validation of skrub pipelines
- `mark_as_X()` and splitting
- choices and tuning

Add user guide page on expressions validation & param search

---

skrub/_expressions/_estimator.py
skrub/_expressions/tests/test_estimators.py
skrub/_expressions/tests/test_parallel_coord.py

This changes the order of metrics in the `ParamSearch.results_` and parallel coordinate plot to put the score on the right (next to the colorbar)
It also gets rid of a warning in `test_multi_scoring`

Change parallel coord order to put score last

---

doc/reference/index.rst
doc/skrub_pipeline_validation.rst
examples/expressions/10_expressions_intro.py
examples/expressions/11_choices.py
skrub/_expressions/_estimator.py
skrub/_expressions/_evaluation.py
skrub/_expressions/_inspection.py
skrub/_expressions/_skrub_namespace.py
skrub/_expressions/tests/test_estimators.py
skrub/_expressions/tests/test_inspection.py

Makes it possible to get some pipelines configured with different choice combinations, when wen want to inspect their output rather than just pick the best with a gridsearchcv or randomizedsearchcv (or when we want to control the validation ourselves)
```
>>> import numpy as np
>>> from sklearn import preprocessing
>>> import skrub
>>> scaler = skrub.choose_from(
...     [
...         preprocessing.MinMaxScaler(),
...         preprocessing.StandardScaler(),
...         preprocessing.RobustScaler(),
...         preprocessing.MaxAbsScaler(),
...     ],
...     name="scaler",
... )
>>> out = skrub.X().skb.apply(scaler)
>>> X = np.asarray([-4.0, 3.0, 10.0])[:, None]
>>> for p in out.skb.iter_pipelines_grid():
...     print("======================================")
...     print("params:", …
```

Add iterator over choice combinations + pipeline param description

---

skrub/_expressions/_parallel_coord.py
skrub/_expressions/tests/test_parallel_coord.py

closes #1367 
alternative to #1385 
needs testing on many pipelines and display combinations to see if it makes things better or worse on average
example on home page:

wrap parallel coordinate plot tick labels

---

skrub/_string_encoder.py

The `StringEncoder` uses the default randomized strategy in its `TruncatedSVD` instance. This PR adds support for passing a `random_state` for reproducible results.
In a side comment this is my first PR in skrub :tada:

Add support for random_state in StringEncoder

---

CONTRIBUTING.rst
doc/install.rst
doc/table_report.py

Fix issue #1345
I have built the documentation, and everything that I changed is displayed correctly. If needed I can upload some printscreens.
The only thing that I could not change is to enable the Tab "From Source" directly through the link for installation, I believe that is because of the embedded HTML that is not reactive.
Also, even in the current version of documentation in scrub, the link to [Advanced Usage for Contributors](https://skrub-data.org/stable/install.html#advanced-usage-for-contributors) does not work; one should enter the link and click the "From Source" tab.
But I think this is not an impeditive to merge this PR.
Please let me know if you think that there is better ways to organize the information that I have changed.

Improve contributing guide

---

skrub/_to_datetime.py

Fixes https://github.com/skrub-data/skrub/issues/1423
`to_datetime` is indeed our only public function using the dispatch mechanism, which creates some trouble due to overloading in Sphinx. [It seems tricky to configure Sphinx overloading behavior](https://github.com/sphinx-doc/sphinx/issues/10359). Fortunately, we can hide it by wrapping the dispatched function.

Fix duplicated doc issue with `to_datetime`

---

CHANGES.rst
skrub/_string_encoder.py
skrub/tests/test_string_encoder.py

Fixes https://github.com/skrub-data/skrub/issues/1402 and add a small footnote in the StringEncoder.

Add stop-words to StringEncoder

---

skrub/_expressions/_skrub_namespace.py

I noticed a typo in the documentation. Quick modification.

typing error "y" vector

---

skrub/datasets/_fetching.py

Closes #1472.
Users that want to load this dataset directly from OpenML can now easily find the reference.
Also, this PR proposes removing a promise I am not sure skrub maintainers are planning to keep.

DOC Rephrasing of employee_salaries dataset description

---

CHANGES.rst
skrub/_dataframe/_common.py
skrub/_reporting/_data/templates/summary-statistics.html
skrub/_reporting/_summarize.py
skrub/_reporting/tests/test_summarize.py

Working on #1398 
skrub sprint at Probabl's 2025-07-09
Adds a column in Stats:
For  `df = pl.DataFrame(dict(a=[1, 2, 1], b=['one', 'three', 'two'], c=[1, 2, 3]))`
~~I need to add tests.~~
Edit: codecov seems fine. So waiting for feedback now.

Add method that checks if a column is sorted

---

examples/data_ops/11_choices.py

This PR suggests a lot of rewording and adds links to references of the choices example. To be useful, this example should be significantly shorter, and most parts detailing the features of the data ops or choices should go to the user guides, in https://github.com/skrub-data/skrub/pull/1529.

Improve choices example

---

doc/version.json

This change was forget during the release process.

MAINT update version.js due to 0.6.1 release

---

pyproject.toml

I noticed that we still broadcast a beta status: https://pypi.org/project/skrub/
I think that we should change this. Here is a PR doing it.

Update our development status

---

doc/modules/data_ops/validation/hyperparameter_tuning.rst
doc/modules/tablereport/exploring_dataframes_interactively.rst
examples/00_getting_started.py

- Removed section on datasets
- Added replace directives
- Split exploration and cleaning sections

DOC - Improving getting started example
